### PR TITLE
[HWKMETRICS-39]fix for JAX-RS warnings and send proper error message

### PR DESCRIPTION
**Pull request by jkandasa**
This fix handles NotAcceptable(406), NotAllowed(405), NotFound(404) and NotSupported(415) exceptions. Returns http response with error message and corresponding status code. For NotFound(404) exception only it returns status code as 400 (Bad request).

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by tsegismont** [comment]
Hey Jeeva, thanks for the PR! Other than the comments inline, can you make sure that each of the cases presented in the JIRA are covered in a test case? You could create an ErrorsITest in the rest-test modules.

Also, I guess you transformed all 400 errors into 404 because of the "Send long parameter value, while int is expected" case detailed in the JIRA. But this is wrong. We shouldn't transform **all** 404 into 400, only those created after a bad conversion. Can you paste the full exception trace here? I'd like to see if we can find anything from the nested cause.

**Comment by jkandasa** [comment]
@tsegismont Hi Thomas, Thank you for the review. I will change code as per your comments. Here is the full exception trace for 404, which is really not 404,
```
GET: http://localhost:8080/hawkular-metrics/test/metrics/numeric/test/data?buckets=999999999999999999999999
Accept: application/json
```

```java
15:43:04,969 WARN  [org.jboss.resteasy.core.ExceptionHandler] (default task-5) failed to execute: javax.ws.rs.NotFoundException: Unable to extract parameter from http request: javax.ws.rs.QueryParam("buckets") value is '999999999999999999999999' for public void org.hawkular.metrics.api.jaxrs.MetricHandler.findNumericData(javax.ws.rs.container.AsyncResponse,java.lang.String,java.lang.String,java.lang.Long,java.lang.Long,java.lang.Integer,org.hawkular.metrics.api.jaxrs.param.Duration)
	at org.jboss.resteasy.core.QueryParamInjector.throwProcessingException(QueryParamInjector.java:43) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.StringParameterInjector.extractValue(StringParameterInjector.java:336) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.StringParameterInjector.extractValues(StringParameterInjector.java:271) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.QueryParamInjector.inject(QueryParamInjector.java:56) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:89) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:112) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.10.Final.jar:]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_31]
Caused by: java.lang.NumberFormatException: For input string: "999999999999999999999999"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) [rt.jar:1.8.0_31]
	at java.lang.Integer.parseInt(Integer.java:583) [rt.jar:1.8.0_31]
	at java.lang.Integer.<init>(Integer.java:867) [rt.jar:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) [rt.jar:1.8.0_31]
	at org.jboss.resteasy.core.StringParameterInjector.extractValue(StringParameterInjector.java:319) [resteasy-jaxrs-3.0.10.Final.jar:]
	... 39 more
```

**Comment by pilhuhn** [comment]
Yes, that above is not a 404 at all. A 400 may be better - see also https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error

**Comment by tsegismont** [comment]
@jkandasa maybe you can check if the exception cause is a NumberFormatException, and, in this case only, return a 400 error.

**Comment by jkandasa** [comment]
@tsegismont @pilhuhn Hi Thomas/Heiko, Thanks for the review, Now `NotFoundExceptionMapper` return a 400 error, if the exception cause is a NumberFormatException, otherwise 404.
Added `ErrorsITest.java` with 5 test cases which covers cases presented in the JIRA(HWKMETRICS-39)

**Comment by tsegismont** [comment]
@jkandasa thanks for the update. I've made some comments on the commits.

**Comment by jkandasa** [comment]
@tsegismont Hi Thomas, Thanks for the comments. I have pushed the changes.

**Comment by jkandasa** [comment]
@tsegismont Travis failed with Protocol Translator module. Could you please re-run Travis CI for this PR?

```Java
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.593 sec <<< FAILURE! - in org.hawkular.metrics.clients.ptrans.fullstack.CollectdITest
shouldFindCollectdMetricsOnServer(org.hawkular.metrics.clients.ptrans.fullstack.CollectdITest)  Time elapsed: 10.589 sec  <<< FAILURE!
java.lang.AssertionError: Could not get metrics list from server: http://127.0.0.1:55988/hawkular-metrics/T6537030b-9c5b-40ee-9fd2-3a79e17c3a101/metrics?type=num, 204
	at org.junit.Assert.fail(Assert.java:88)
	at org.hawkular.metrics.clients.ptrans.fullstack.CollectdITest.getServerData(CollectdITest.java:251)
	at org.hawkular.metrics.clients.ptrans.fullstack.CollectdITest.shouldFindCollectdMetricsOnServer(CollectdITest.java:182)
````

**Comment by tsegismont** [comment]
Thank you @jkandasa , excellent work!

**Pull request merged**
