### PR TITLE
HWKMETRICS-128

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by mwringe** [comment]
screenshot from 2015-08-26 17 46 43

Looks good. I find the SHA1 hash to be a bit confusing on that page. Maybe make it a bit smaller and put it on a new line with a Git SHA1 prefix?

Accessing the page in json returns:
{"Implementation-Version":"0.7.0-SNAPSHOT","Built-From-Git-SHA1":"664f742231c634d1c5754757307797f4cfe21235","name":"Hawkular-Metrics"}

Is there any way you can make it so that the name is the first element being returned?

**Comment by stefannegrea** [comment]
Unfortunately I do not see an easy way to sort the JSON output. I tried a few permutations with the Map implementations but the output is identical. I am not sure if the JSON mapper is the one that dictates the final output or the map itself.

**Comment by stefannegrea** [comment]
I pushed a fix for the html output, the SHA1 is on a separate line and with smaller font. 
screen-status-page

**Comment by burmanm** [comment]
@JsonPropertyOrder ? Although I fail to see any reason in sorting json

**Comment by stefannegrea** [comment]
There is no mapping class right now with all the properties to use the annotation. I switched to a simple Map<String,String> since the status and default handlers just return a few information fields.

**Comment by stefannegrea** [comment]
Please retest

**Comment by stefannegrea** [comment]
Retest this please

**Comment by mwringe** [comment]
Looks good to me. Merging

**Pull request merged**
