### PR TITLE
Perf debug

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by burmanm** [comment]
..why?

**Comment by FilipB** [comment]
To find out if perf test failures are caused by driver version. There will be jira once it's clear what's causing it.

**Comment by FilipB** [comment]
The issue is still visible - https://issues.jboss.org/browse/HWKMETRICS-542

**Comment by stefannegrea** [comment]
I will close this since @jsanda  is working on a fix with the current driver version.

**Pull request closed without merging**
