### PR TITLE
HAWKULAR-1121 Store string as a key on PublishCache

### PR DESCRIPTION
**Pull request by lucasponce**
A bug in an integration test on hawkular-services (https://issues.jboss.org/browse/HAWKULAR-1121) has masked a problem not detected until now.
Storing an object as a key for published cache requires to share same classloader between libraries used by metrics and alert.
So a workaround is to use a primitive type as proposed on this fix.
Counter part on alerting and fixed itest on hawkular-services are on the way.
/cc @stefannegrea @jshaughn

### CODE REVIEW

**Comment by jshaughn** [comment]
I can't quite understand what a change from MetricId key to String solves the problem.  String is a class just like MetricId, it's not a Java primitive.   So, I'm not sure the classloader analysis is correct.  The equals and hascode impls of metricId look OK.  But, you have shown that it works with String key and not MetricId key, so I guess I'm OK with the change if necessary.

**Comment by lucasponce** [comment]
I guess point is that MetricId is not serializable
http://infinispan.org/docs/stable/user_guide/user_guide.html#_plugging_infinispan_with_user_defined_externalizers
Perhaps, a workaround is simply to make it serializable.
It should work.
Please don't merge this one, I'm going to test that.

**Comment by lucasponce** [comment]
Implemented Serializable on MetricId.
I hope travis CI can confirm that this change has not any regression on any perf task.

**Comment by lucasponce** [comment]
Finally storing a string as a key for PublishCache.
Confirmed that using MetricId on local ISPN cache from different isolated apps it loads the MetricId class from different classloaders, so local cache fails to validates keys in this scenario.
Other alternatives like moving local cache into a distributed one to force serialization of objects are costly than a string conversion.

**Comment by stefannegrea** [comment]
@lucasponce, do you mind opening a Hawkular Metrics JIRA for this issue too? Also, once this gets merged in master, do you mind opening a second PR agains the 0.19.0 release branch?

**Comment by jshaughn** [comment]
Fixes https://issues.jboss.org/browse/HWKMETRICS-475

**Comment by jshaughn** [comment]
LGTM.

**Comment by stefannegrea** [comment]
Thank you @lucasponce and @jshaughn!

**Pull request merged**
