### PR TITLE
[HWKMETRICS-120] Start Thrift Server in embedded Cassandra service.

### PR DESCRIPTION
**Pull request by metlos**
Please review.

The JIRA mentions problems with long shutdown times after this change. We should investigate that before merging this.

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
Thanks @metlos !

**Pull request merged**
