### PR TITLE
HWKMETRICS-348

### PR DESCRIPTION
**Pull request by auszone**
generateRates in GenerateRateITest is failing.
It calls generateRate at first and then invoke findRateData.
It seems recalculate and overwrite the rate.
This commit just makes the test pass.

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
@auszone, can you please fix the failing build first? There is a problem with the header for `GenerateRateITest`. Every time a file is modified it needs to reflect the year of the last change in the header. Some of the files have already been modified in 2016 so they do not need this change, however that file was not.

**Comment by auszone** [comment]
You mean I just need to simply change the 2015 to 2016 in the license header?

**Comment by pilhuhn** [comment]
On 11 Feb 2016, at 4:29, Austin Kuo wrote:

> You mean I just need to simply change the 2015 to 2016 in the license 
> header?

Rather 2015-2016

When you build locally the licence checker should complain (until you
have it right :-)

Maven `-Dlicense:format` (iirc) may be of help here

**Comment by auszone** [comment]
@pilhuhn I think you mean `mvn license:check` :) Got it.

**Comment by pilhuhn** [comment]
On 11 Feb 2016, at 10:14, Austin Kuo wrote:

> @pilhuhn I think you mean `mvn license:check` :) Got it.

Right and :format

**Comment by stefannegrea** [comment]
Thanks @auszone!

**Pull request merged**
