### PR TITLE
SonarQube issues - try-with and entrySets

### PR DESCRIPTION
**Pull request by burmanm**
These fix some critical issues in other functions than REST-API. Use of entrySet instead of keySet when all the entries are iterated over and use of try-with instead of Closeable (and also fix potential resource leak at the same time).

### CODE REVIEW

**Comment by tsegismont** [comment]
LGTM, except, that the import order is not correct. See https://github.com/hawkular/hawkular-build-tools/blob/master/ide-configs/eclipse/hawkular-eclipse-preferences-java-codestyle-organizeimports.importorder

Can you update your settings and push a new commit to minimize this diff and future ones?

**Comment by burmanm** [comment]
I have https://github.com/hawkular/hawkular-build-tools/blob/master/ide-configs/idea/settings.jar imported. It generates this kind of output.

**Comment by tsegismont** [comment]
Le 04/03/2015 15:45, Michael Burman a écrit :
> I have
> https://github.com/hawkular/hawkular-build-tools/blob/master/ide-configs/idea/settings.jar
> imported. It generates this kind of output.

Then settings.jar is wrong :)

**Comment by lucasponce** [comment]
I put a fix for it in the last settings.jar, the order is still incorrect ?

Thanks,
Lucas

**Comment by tsegismont** [comment]
Maybe Micke imported an older one

**Comment by burmanm** [comment]
"Current branch master is up to date.". So either IDEA is bugging with it or yes.. could be IntelliJ though, as it now shows mixture of rhq import order & hawkular order in the same page.

**Comment by burmanm** [comment]
I'll make an issue on the hawkular-build-tools, settings. jar doesn't include our special rules of imports. So wasn't my IntelliJ

**Comment by tsegismont** [comment]
Micke, any chance you manually change the settings in IDEA before IJ settings.jar is updated? Let's merge this PR soon.

**Comment by burmanm** [comment]
Hep, here you go (forgot the whole thing..). I still have different alphabetic order in SchemaManager, does that need fixing also?

**Comment by tsegismont** [comment]
No, that's for the next PR ;) Thanks Micke!

**Pull request merged**
