### PR TITLE
HWKMETRICS-439 Create driver usage metrics

### PR DESCRIPTION
**Pull request by tsegismont**
Previously driver usage was printed regularly in the logs.
With this change, driver usage metrics will be publish to the registry.

### CODE REVIEW

**Comment by tsegismont** [comment]
It seems GH has issues (see GH status). We'll have to trigger tests again later.

**Comment by burmanm** [comment]
Hi, any chance you could rebase?

**Comment by tsegismont** [comment]
Done

**Comment by jsanda** [comment]
A fix for the test failure was merged to master. Could you please rebase again?

**Comment by tsegismont** [comment]
Done

**Comment by jsanda** [comment]
retest this please

**Pull request merged**
