### PR TITLE
Upgrade to hawkular-parent 14

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by tsegismont** [comment]
Given that Mockito and Wildfly Maven Plugin are now declared in parent POM, shouldn't the Metrics POM files be updated, in order not to override parent definitions?

**Comment by ppalaga** [comment]
@tsegismont yes, this is a good occasion, but I cannot promise to find the time to do that for metrics. Feel free you or anyone else to take 4c52582 , place the needed fixes on top of it and submit as a separate PR. But if there is nobody to do that now, I'd find it better to merge like this and create a followup Jira to address it later.

**Pull request merged**
