### PR TITLE
Upgrade to parent 12

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
Do not want to upgrade to Parent 12 because of the long and complex version numbers for build artifacts.

**Comment by tsegismont** [comment]
I don't understand. The changes in parent POM should just add manifest entries.

**Comment by ppalaga** [comment]
@stefannegrea , as @tsegismont said already, this change touches neither version numbers in pom.xml files nor artifact file names. It just adds git related entries into manifests of jars, wars and ears. That is acceptable, is it not?

**Comment by stefannegrea** [comment]
@ppalaga thanks for the clarification. It all makes sense now, I will merge the change right away. 

@ppalaga, thank you the PR.

**Pull request merged**
