### PR TITLE
Upgrade to hawkular-parent 21

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@stefannegrea is this just the usual "fails sometimes" that only needs a CI restart?

**Comment by tsegismont** [comment]
Not sure what happened. The server port offset got a strange value. 
Restarted the build.

**Comment by tsegismont** [comment]
It looks like it's not an intermittent failure. I suppose you tried the build on your box?

**Comment by ppalaga** [comment]
> you tried the build on your box?

No, I have not.

> The server port offset got a strange value.

There is a wildfly-maven-plugin upgrade from 1.1.0.Alpha2 to 1.1.0.Alpha3. Maybe they changed something in that area.

**Comment by tsegismont** [comment]
> There is a wildfly-maven-plugin upgrade from 1.1.0.Alpha2 to
> 1.1.0.Alpha3. Maybe they changed something in that area.

Yes, see my email in the devel list.

**Comment by tsegismont** [comment]
We can't upgrade parent POM until the issue is fixed in Wildfly Maven Plugin.

**Pull request closed without merging**
