### PR TITLE
Rename module hawkular-alerts-openshift

### PR DESCRIPTION
**Pull request by jshaughn**
Rename module hawkular-alerts-openshift to hawkular-metrics-openshift-alerting.

The current naming is confusing as it overlaps with the module and artifact naming in hawkular alerting itself.

@mwringe hopefully you are OK with this.

### CODE REVIEW

**Comment by mwringe** [comment]
it doesn't matter to me

I was just keeping it consistent with the other naming in Hawkular Metrics, I don't know why its better now have more inconsistent naming.

What does the 'hawkular-alerts-openshift' module in alerting do exactly? I thought all the OpenShift integration stuff was in the Hawkular Metrics github repo?

**Comment by jshaughn** [comment]
> What does the 'hawkular-alerts-openshift' module in alerting do exactly? I thought all the OpenShift integration stuff was in the Hawkular Metrics github repo?

You're right, all of the openshift stuff is in Hmetrics.   The problem for me is the "hawkular-alerts-" prefix, which makes it look like an Halerts module/artifact.  Nearly all other modules in Hmetrics are prefixed with 'hawular-metrics-', so to line up with the existing modules and avoid confusion with Halerts modules, I proposed this change.

I actually think this may be a little more consistent with the existing stuff.  At least in my IDE the maven projects line up better with everything for the OS container dist being prefixed 'hawkular-metrics-openshift'.   So, please merge and make me happy, unless you really object, in which case  I'll just close this PR.

**Comment by jshaughn** [comment]
retest this please

**Comment by stefannegrea** [comment]
The module has never been published in an official release so now it's the best time to rename it. The changes proposed by @jshaughn make the purpose of that module clear.

**Comment by stefannegrea** [comment]
Thank you @jshaughn!

**Pull request merged**
