### PR TITLE
HWKMETRICS-176 REST: make sure all POST requests with empty body return 400 Empty payload

### PR DESCRIPTION
**Pull request by tsegismont**
Updates handlers and added tests. Also made the behavior consistent across endpoints.

### CODE REVIEW

**Comment by burmanm** [comment]
Like discussed in the IRC, I would go for a filter that would reject all the "POST"-requests that have empty payload. Instead, if we want to set something empty, the semantics would be using "PUT" or "DELETE" instead.

**Comment by tsegismont** [comment]
Yeah, I had started to write an interceptor and will resurrect it. It 
will check if body is null. I also had in mind to make sure that a List 
body or Map body is not empty. What do you think?

**Comment by pilhuhn** [comment]
Couldn't that live in the handler code? Check for body == null or body.length==0 should not be too hard and it is much more obvious than in a filter or interceptor

**Comment by tsegismont** [comment]
Le 10/07/2015 11:53, Heiko W. Rupp a écrit :
> Couldn't that live in the handler code? Check for body == null or
> body.length==0 should not be too hard and it is much more obvious than
> in a filter or interceptor

I started with the interceptor and did not push it for this reason. But 
it's true experience has shown it's wasn't always implemented or nor 
consistent across endpoints. Interceptor can help here.

**Comment by tsegismont** [comment]
I've pushed two commits which introduce automated null and empty collection/map checking. Now everyone can get a feeling of what the code looks like.

**Comment by tsegismont** [comment]
Rebased on master. @burmanm would you mind to finish the review (last two commits)?

**Pull request merged**
