### PR TITLE
HWKMETRICS-357 Rx computation threads may block while iterating over C* rows

### PR DESCRIPTION
**Pull request by tsegismont**
Implemented a ResultSetToRowsTransformer, with backpressure support.

### CODE REVIEW

**Comment by tsegismont** [comment]
**Please do not merge yet**

My branch is based on top of #464 , which is not merged yet. I'll rebase this PR as soon as it is.

I've created this PR to share the code and make it possible for others to review.

**Comment by tsegismont** [comment]
Rebased on master.

**Comment by jsanda** [comment]
I have not had a chance to review in detail yet, but it seems like this functionality should live closer to the RxSession class, possibly as part of the implementation since we want everything with RxSession to be async by default.

**Comment by tsegismont** [comment]
@jsanda the transformer is in the rx-java-driver module. Is that what you meant?

**Comment by jsanda** [comment]
That is part of it. Everywhere we iterate over a result set we call,

 ```compose(new ResultSetToRowsTransformer())```

Admittedly this is no worse off than the current code where we call ```flatMap(Observable::from)``` everywhere we iterate over a result set; however, it would be nice if we could encapsulate this so we are not having to repeat it every place we iterate over a result set.

**Comment by tsegismont** [comment]
We could add an ExecuteStatementTransformer, which turns an Observable<Statement> into an Observable<Row>. At the price of having to update the data access layer interface, so that it no longer returns Observable<ResultSet>.

**Comment by tsegismont** [comment]
Or duplicate methods in RxSession so that there is one version returning Observable<ResultSet> and another one returning Observable<Row>.

Data Access Layer update would be still required.

**Comment by jsanda** [comment]
> We could add an ExecuteStatementTransformer, which turns an Observable into an Observable

Not sure I like the idea of returning something other than an Observable. Can you show a pseudo code example of what this might look like?

**Comment by tsegismont** [comment]
This

```java
package org.hawkular.rx.cassandra.driver;

import com.datastax.driver.core.Row;
import com.datastax.driver.core.Statement;

import rx.Observable;
import rx.Observable.Transformer;

public class StatementToRowsTransformer implements Transformer<Statement, Row> {
    private final RxSession rxSession;

    public StatementToRowsTransformer(RxSession rxSession) {
        this.rxSession = rxSession;
    }

    @Override
    public Observable<Row> call(Observable<Statement> statementObservable) {
        return statementObservable.flatMap(statement -> {
            return rxSession.execute(statement).compose(new ResultSetToRowsTransformer());
        });
    }
}

```

**Comment by tsegismont** [comment]
@jsanda I added a bunch of `executeAndFetch` methods to `RxSession`. Tell me if it looks like what you had in mind. In this case, I'll update the Javadoc before merging, so that the developer knows he should use `execute` only if he wants to use methods like `ResultSet#wasApplied`

**Comment by tsegismont** [comment]
@jsanda any chance you can review the second commit sometime soon?

**Comment by jsanda** [comment]
Sorry for the delay. I was out on PTO most of last week. I will get back to reviewing this today.

**Comment by jsanda** [comment]
Overall I think that the changes look good, but I do have a couple questions. First, can you add some automated tests for the transformer? Secondly, would you mind giving a walk through of the changes? I really don't have much experience with implementing transformers, and I am not familiar with custom producers.

If you think that adding tests will be a lot of work, then I am ok with doing that as part of a separate ticket.

**Comment by tsegismont** [comment]
Le 15/03/2016 04:26, jsanda a écrit :
> Overall I think that the changes look good, but I do have a couple
> questions. First, can you add some automated tests for the transformer?

I will add some unit tests. As for integration tests, we know that the 
current suite passes, but I believe there is not test for large (bigger 
than driver fetch size) data sets. Will check.

> Secondly, would you mind giving a walk through of the changes? I really
> don't have much experience with implementing transformers, and I am not
> familiar with custom producers.

I planned to write a blog post about this PR. A transformer is not too 
complicated in theory, it's a way to encapsulate a chain of 
transformations into a separate class, which is nice for testability and 
readability. The producer is the actual tricky part.

>
> If you think that adding tests will be a lot of work, then I am ok with
> doing that as part of a separate ticket.

I will update this PR.

**Comment by tsegismont** [comment]
@jsanda I pushed two commits with the Javadoc for RxSession and a unit test for the transformer. I checked in the itests, the statistics itests work on a more than 10 thousands data points, so there's no need to add a new one. When this PR is merged, I will create the blog post.

**Comment by tsegismont** [comment]
The build failed again in the rest-tests with Hawkular server module. I filed HWKMETRICS-371 so that this issue doesn't block this PR.

**Comment by stefannegrea** [comment]
@tsegismont, we follow the rule to merge PRs only when the Travis and perf-testing builds pass.

**Comment by tsegismont** [comment]
Generally? Yes. Absolutely? No.

We have ignored Travis failures from time to time when we had recurring, 
unrelated-to-the-changes problems like this one.

In fact, all my PRs for proper Accounts integration were merged in spite 
of it.

I filed a ticket to track the issue and will work on it as soon as I 
can. If you feel it should block all PRs, then maybe you can have a look 
at it?

**Comment by jsanda** [comment]
I'll go ahead and merge this but I am generally -1 on mocking 3rd party libraries. Mocking is about controlling behavior or implementation. With 3rd party libraries, we have no control over the behavior. Other than that, everything looks good, and I look forward to the blog post!

**Comment by tsegismont** [comment]
We talked about a unit test and I can't see how to do it without mocking
the driver Session. I agree that unit tests are not enough, however there
is already a great coverage with all the integration tests we have in the
rest-tests module. Thank you for merging John. I will try to get the blog
post ready this week.

2016-03-21 1:32 GMT+01:00 jsanda <notifications@github.com>:

> I'll go ahead and merge this but I am generally -1 on mocking 3rd party
> libraries. Mocking is about controlling behavior or implementation. With
> 3rd party libraries, we have no control over the behavior. Other than that,
> everything looks good, and I look forward to the blog post!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hawkular/hawkular-metrics/pull/465#issuecomment-199070020>
>



-- 
Thomas Segismont
JBoss ON Engineering Team

**Pull request merged**
