### PR TITLE
HWKMETRICS-16 ptrans has no integration tests

### PR DESCRIPTION
**Pull request by tsegismont**
The goal isn't to test a full collectd/ptrans/metrics stack (this could be done in another PR)

The goal is to verify that when metrics REST API changes, ptrans isn't broken.
It happened and I believe there's at least one metrics release under the RHQ org which has a broken ptrans.

So now the ptrans module is built after rest-tests.
It starts a Wildfly server with the metrics REST API.
Then RestForwardingHandlerITest sends a metric through a RestForwardingHandler and verifies that it landed in the database.

Side work (in separate commits)
Move rest-tests Wildfly configuration out of the standard tests resources directory.
Updated rest-tests POM file

### CODE REVIEW

**Comment by stefannegrea** [comment]
Good changes!

**Comment by tsegismont** [comment]
Thanks!

**Comment by pilhuhn** [comment]
Great stuff, @tsegismont

**Comment by tsegismont** [comment]
Le 12/02/2015 10:07, Heiko W. Rupp a écrit :
> Great stuff, @tsegismont <https://github.com/tsegismont>
>

Thanks!

**Pull request merged**
