### PR TITLE
HAWKULAR-1121 Store string as a key on PublishCache for 0.19.0 branch

### PR DESCRIPTION
**Pull request by lucasponce**
Enable additional debug logging

### CODE REVIEW

**Comment by lucasponce** [comment]
Same commit for release/0.19.0 branch.
/cc @stefannegrea

**Comment by FilipB** [comment]
retest this please

**Comment by lucasponce** [comment]
@FilipB do you mean to re-run the CI jobs ?

**Comment by stefannegrea** [comment]
Thanks @lucasponce!

**Pull request merged**
