### PR TITLE
HWKMETRICS-404 Cassandra Driver timeouts during the build

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jsanda could you please comment?

**Comment by jsanda** [comment]
I'm not sure why the build fails for you, but I am not comfortable with increasing timeouts solely because requests time out only in your dev environment.

**Comment by ppalaga** [comment]
I'd be happy with any working solution. How about making the timeouts configurable?

**Comment by jsanda** [comment]
Making it configurable would be great.

**Comment by ppalaga** [comment]
> Making it configurable would be great.

Would a system property (say `hawkular.cassandra.driver.readTimeout`) be good enough?

**Comment by ppalaga** [comment]
4a9fa24 replaces the original version with hardcoded timeouts. The timeouts are now read from `cassandra.driver.read-timeout-ms` system property.

**Comment by stefannegrea** [comment]
Closing this PR since it is no longer relevant.

**Pull request closed without merging**
