### PR TITLE
Bump alerting src-dep for new perf enhancements and to stay in sync

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by jshaughn** [comment]
retest this please

**Comment by jshaughn** [comment]
retest this please you stupid jerk, and how about pass this time!

**Comment by FilipB** [comment]
retest this please

**Comment by jshaughn** [comment]
@stefannegrea Please merge.

**Comment by stefannegrea** [comment]
Thank you @jshaughn!

**Pull request merged**
