### PR TITLE
Wildfly11 update for 0.21.x

### PR DESCRIPTION
**Pull request by rubenvp8510**
This PR depends on a release of new hawkular-parent pom, first need to merge this PR: https://github.com/hawkular/hawkular-parent-pom/pull/104

Also, it depends on one PR for alerts: https://github.com/hawkular/hawkular-alerts/pull/500 and a new release of alerts, not sure if we still need alerts for this or we can take it off.

WDYT @jsanda?

### CODE REVIEW

**Comment by jsanda** [comment]
It looks like we need to do the parent pom update first based on the error in travis:

```
[ERROR]   The project org.hawkular.metrics:hawkular-metrics-parent:0.21.12.Final (/home/travis/build/hawkular/hawkular-metrics/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.hawkular.metrics:hawkular-metrics-parent:0.21.12.Final: Could not find artifact org.hawkular:hawkular-parent:pom:58 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public-jboss/) and 'parent.relativePath' points at wrong local POM @ line 23, column 11 -> [Help 2]
```

**Comment by rubenvp8510** [comment]
@jsanda yes, that is why I sent a PR to the parent-pom: https://github.com/hawkular/hawkular-parent-pom/pull/104

**Comment by jsanda** [comment]
When updates are made to the parent pom, it has to be released so that it is published to nexus. Your PS is making changes in the release/0.21.0 branch which is on an older version of the parent pom. I am a little concerned that updating to the latest parent pom in the release/0.21.0 branch might introduce some additional dependency changes. Can we instead update the guava dependency directly in the the hawkular-metrics and hawkular-alerts projects?

**Comment by rubenvp8510** [comment]
@jsanda ok, I can update the dependencies directly here, but I think we still need to merge the other PR on the parent pom because latest versions of metrics could need it.

**Pull request merged**
