### PR TITLE
HWKMETRICS-352 Add integration tests to metric input from the bus

### PR DESCRIPTION
**Pull request by tsegismont**
HWKMETRICS-352 Add integration tests to metric input from the bus

Configured the input queues and inserted data topics to be accessible to remote clients

The integration test connects as a remote client, sends input data and listens to inserted data.
 Inserted data events must match input data.

### CODE REVIEW

**Comment by stefannegrea** [comment]
@tsegismont the configuration that comes along with the changes looks invalid.

**Comment by tsegismont** [comment]
@stefannegrea I just tried again, it passes on my box... Looking.

**Comment by tsegismont** [comment]
Looks like a Maven version incompatibility issue. It's not the Wildfly config which is the cause, but the user definition in the Wildfly Maven Plugin.

**Comment by tsegismont** [comment]
@stefannegrea I just pushed a fix to the Wildfly Maven Plugin declaration. It still works on my box. Let's see how it works on Travis.

**Comment by tsegismont** [comment]
@stefannegrea looks like Travis is happy now

**Comment by stefannegrea** [comment]
Thanks @tsegismont!

**Pull request merged**
