### PR TITLE
HWKMETRICS-297 Incorporate static blocks into the REST API documentation

### PR DESCRIPTION
**Pull request by tsegismont**
Currently, the REST API doc source is generated by parsing the Swagger JSON output.

We should be able to incorporate static Asciidoctor blocks into the output.

This would allow to move duplicated notes from Swagger annotations to a static `Overview` section.

### CODE REVIEW

**Comment by tsegismont** [comment]
To test this on your machine:
- run `mvn clean compile -Pdocgen` in the `api/metrics-api-jaxrs` module
- open the Asciidoc file: `api/metrics-api-jaxrs/target/generated/rest-metrics.adoc`

**Comment by tsegismont** [comment]
Please do not merge yet. I'd like to gather feedback on the base [documentation plan](https://raw.githubusercontent.com/tsegismont/hawkular-metrics/jira/HWKMETRICS-297/api/metrics-api-jaxrs/src/main/rest-doc/base.adoc)

**Comment by tsegismont** [comment]
I went ahead and started to write the base documentation. I believe we can review the content now and come back to it later, if we get comments after this PR is merged.

**Comment by stefannegrea** [comment]
@tsegismont, can we postpone this to 0.9.0?

**Comment by tsegismont** [comment]
Le 08/10/2015 23:17, Stefan Negrea a écrit :
> @tsegismont <https://github.com/tsegismont>, can we postpone this to 0.9.0?

Answered the same question on JIRA yesterday:
http://red.ht/1LlgNGu

**Comment by stefannegrea** [comment]
Then let's postpone this to 0.9.0. I will update the JIRA too.

**Comment by stefannegrea** [comment]
Master is ready to accept PRs against 0.9.0. 

@tsegismont, do you mind rebasing your work on master so we can merge it?

**Comment by tsegismont** [comment]
@stefannegrea done

**Comment by stefannegrea** [comment]
Thanks @tsegismont!

**Pull request merged**
