### PR TITLE
POM cleaning and JAX-RS duplications removal

### PR DESCRIPTION
**Pull request by tsegismont**
POM cleanup

- removed redundant dependency declarations
- moved log4j and slf4j-over-log4j to test scope, otherwise they end up in the JAX-RS implementations WAR files
- removed codehaus jackson from JAX-RS 2.0 WAR file

Eliminate as much duplicated code as possible between JAX-RS implementations.

### CODE REVIEW

**Comment by tsegismont** [comment]
The two most important things here are:
- reduced war file size
- restriction of JAX-RS differences to a minimum (handlers, exception mappers, filters, interceptors, Jackson config)

**Comment by tsegismont** [comment]
@jsanda could you review with one as well? Thanks!

**Comment by jsanda** [comment]
Looks like you need to rebase. After that, I think we are ready to merge.

**Comment by tsegismont** [comment]
Le 09/09/2015 16:45, jsanda a écrit :
> Looks like you need to rebase. After that, I think we are ready to merge.

Done

**Pull request merged**
