### PR TITLE
Move maven plugins to hawkular-parent

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by tsegismont** [comment]
I would not merge this one before we release the final version under "rhq-project" org.

**Comment by stefannegrea** [comment]
I concur with @tsegismont

**Comment by ppalaga** [comment]
Yes, this PR it is partly introducing the new naming convention, but that is really unimportant for that release. The release will work the same. I have already released hawkular-parent version 2 with plugins and config taken from metrics due to that the plugins and their config in metrics are obsolete and should be removed immediately.

**Comment by tsegismont** [comment]
@ppalaga I'm going to put your work in a specific branch and close this PR. After we've moved to the Hawkular org, I'll take care of merging it.

**Comment by ppalaga** [comment]
84e8104 is a rebase on current master plus upgrade to hawkular-parent version 4

**Comment by ppalaga** [comment]
60afe23 is a rebase on current master plus upgrade to hawkular-parent version 5 plus a fix for 	HAWKULAR-23

**Comment by ppalaga** [comment]
60afe23 is a rebase on current master plus upgrade to hawkular-parent version 5 plus a fix for 	HAWKULAR-23

**Comment by ppalaga** [comment]
7f89892 removes `-SNAPSHOT` from the `hawkular-parent` version. Othere than that it is the same as 60afe23 - i.e. a rebase on current master plus upgrade to hawkular-parent version 5 plus a fix for HAWKULAR-23

**Comment by pilhuhn** [comment]
Now after the release  + move, can that be merged, @stefannegrea @tsegismont ?

**Comment by tsegismont** [comment]
I've restarted a build on Travis to check the PR is still correct. I'll merge it if Travis is happy.

**Comment by tsegismont** [comment]
Thanks @ppalaga

**Pull request merged**
