### PR TITLE
Upgrade to hawkular-parent 25

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by tsegismont** [comment]
Thanks Peter. Could you also remove the Wildfly Maven Plugin version overwrite? Don't lose time running the build. Travis can do this for you :)

**Comment by tsegismont** [comment]
@ppalaga do you plan to update this PR sometime soon?

**Comment by ppalaga** [comment]
@tsegismont sorry, I have overseen your first message. I rebased on top of current master and added 67aa4f5

**Comment by tsegismont** [comment]
Perfect, thanks Peter!

**Pull request merged**
