### PR TITLE
[HWKMETRICS-456] use DateTieredCompaction and table default TTL

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
There is a lot of code duplication in DataAccess. Would it be possible to have the method without TTL call the method with TTL and make a decision there as to what statement to use?

**Comment by stefannegrea** [comment]
I am merging this as-is and will open another PR to remove some of the code duplication resulting from the TTL and non-TTL methods.

**Pull request merged**
