### PR TITLE
[HWKMETRICS-700] [HWKMETRICS-701] Fixes BufferUnderflow

### PR DESCRIPTION
**Pull request by burmanm**
Updates compression-gorilla to 2.0.3 and fixes the regression in Gorilla V1

### CODE REVIEW

**Comment by FilipB** [comment]
Exception is still visible

**Comment by burmanm** [comment]
Rebased from test_fixes (PR #855)

**Comment by FilipB** [comment]
I'm no longer able to reproduce. There has been no exception during past 4.5 hours.

**Comment by FilipB** [comment]
Ok to merge, haw-metrics-perf-stability-test failed only for gauges because of other overlapping test run.

**Comment by stefannegrea** [comment]
Thank you @burmanm!

**Pull request merged**
