### PR TITLE
Performance Testing

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by stefannegrea** [comment]
Please do not merge this pull request! This is for trying different performance loads.

**Comment by FilipB** [comment]
First commit increased throughput for gauges from ~17000 to 45409

**Comment by FilipB** [comment]
Second commit decreased throughput for gauges from ~17000 to 15303

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
This PR is no longer needed.

**Pull request closed without merging**
