### PR TITLE
Bind metrics service to JNDI

### PR DESCRIPTION
**Pull request by pavolloffay**
Bind metrics service to JNDI so other hawkular components can use inject it.

@jsanda @burmanm could you please review?

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jsanda** [comment]
Couldn't we achieve the same functionality with a CDI producer which would not require EJB?

**Comment by pavolloffay** [comment]
When I tried to bind it in ``MetricsServiceLifecycle``  I got ``WFLYNAM0043: Naming context is read-only``


This is the same approach as for Inventory-Pinger.

**Comment by jsanda** [comment]
>This is the same approach as for Inventory-Pinger.

Be that as it may, I would prefer to avoid introducing the additional dependencies unless we really have to. More often than not we have found that CDI alone with EJB provided the functionality we need.

**Comment by pavolloffay** [comment]
@jsanda now without EJB

**Comment by pavolloffay** [comment]
injection works but in data mining Im getting this http://pastebin.com/5NgD0UHP

**Comment by pavolloffay** [comment]
@jsanda can it go to the master?

**Pull request merged**
