### PR TITLE
Pre-commit hook sample for JAX-RS diffs

### PR DESCRIPTION
**Pull request by tsegismont**
Metrics dev should add this hook to their local repo. Whenever we introduce changes which impact the diff, the file will show up on GH. So it will help both the developer and the reviewer to make sure the impls do not diverge.

### CODE REVIEW

**Comment by tsegismont** [comment]
I've checked the diff file and fixed something in `MetricDefinition` classes. Other differences look expected to me.

**Comment by stefannegrea** [comment]
> Seulement dans api

The diff file that you committed has a few keywords in French, could you use/force English (or any language) so there is no churn in the file when somebody commits with a different system locale?

Excellent work! If we resolve the language issue, this PR is ready to be merged.

**Comment by tsegismont** [comment]
@stefannegrea thanks, and nice catch!

I've rebased the PR on master and added a commit (2f8a146) to address the language issue.

**Comment by stefannegrea** [comment]
Thanks @tsegismont !

**Pull request merged**
