### PR TITLE
[HWKMETRICS-587] Use the code from master that randomly generates ten…

### PR DESCRIPTION
**Pull request by stefannegrea**
…ant ids to avoid tenant conflicts.

### CODE REVIEW

**Comment by jsanda** [comment]
@stefannegrea is this PR meant for the release/0.23.0 branch?

**Comment by stefannegrea** [comment]
@jsanda, it is meant for 0.21.x release stream. There are two PRs blocked due to these tests failing.

**Comment by jsanda** [comment]
retest this please

**Comment by jsanda** [comment]
Thanks for the clarification. I am actually not going to worry about the perftest since this PR only updates test code.

**Pull request merged**
