### PR TITLE
Change Cassandra to use timeslices instead of TTL

### PR DESCRIPTION
**Pull request by burmanm**
This is WIP PR, but should in the end solve following tickets:

* [HWKMETRICS-189](https://issues.jboss.org/browse/HWKMETRICS-189)
  * [HWKMETRICS-192](https://issues.jboss.org/browse/HWKMETRICS-192)
  * [HWKMETRICS-193](https://issues.jboss.org/browse/HWKMETRICS-193)
  * [HWKMETRICS-194](https://issues.jboss.org/browse/HWKMETRICS-194)
  * [HWKMETRICS-195](https://issues.jboss.org/browse/HWKMETRICS-195)
* [HWKMETRICS-191](https://issues.jboss.org/browse/HWKMETRICS-191)
* [HWKMETRICS-127](https://issues.jboss.org/browse/HWKMETRICS-127)
* [HWKMETRICS-3](https://issues.jboss.org/browse/HWKMETRICS-3) for data table

This one will also remove tags from individual data points. Currently all the tests at the time of branching work, but new added tests fail still occasionally (something to do with timing and sorting).

Do not merge yet, will require more tests and some more features.

### CODE REVIEW

**Comment by stefannegrea** [comment]
Please do not merge this PR until 0.6.0 is released.

**Comment by jsanda** [comment]
@burmanm I sincerely appreciate the ambitious effort, but I really do not want to see a PR that covers all of those tickets :)  How about we tackle HWKMETRICS-194, HWKMETRICS-195, and HWKMETRICS-127 separately? Someone else can work on HWKMETRICS-127 in parallel, and I would prefer to get the initial changes into master before we take on 194 and 195.

**Comment by burmanm** [comment]
Yeah, I can postpone -194, -195 and -127 out of this ticket (as I didn't really do anything for them)

**Comment by stefannegrea** [comment]
Can we close this PR and port any work that is still applicable to another future PR?

**Comment by stefannegrea** [comment]
Just chatted with @burmanm  and will close this PR. Any work that can be salvaged, will be ported to a new PR.

**Pull request closed without merging**
