### PR TITLE
HWKMETRICS-29 Create method return codes should be consistent

### PR DESCRIPTION
**Pull request by tsegismont**
HWKMETRICS-29 Create method return codes should be consistent

### CODE REVIEW

**Comment by tsegismont** [comment]
I've added a new ExceptionMapper: ReaderExceptionMapper

https://github.com/tsegismont/hawkular-metrics/blob/jira/HWKMETRICS-29/api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/ReaderExceptionMapper.java

It catches all exceptions thrown my MessageBodyReader chains. Without such a mapper, it's not possible to control the format of the error returned to the user. For example, Jackson built-in exception mappers create a plain text response., whereas our application code uses a JSON object with a "errorMsg" field. Well, a growing portion of application code does ;)

**Comment by tsegismont** [comment]
@stefannegrea , @jsanda could one of you please review/merge now that Travis says it's happy? Thanks

**Comment by burmanm** [comment]
There's in websocket branch this PR already: https://github.com/hawkular/hawkular-metrics/pull/163 which does the same thing, but just quite a bit differently..

**Comment by tsegismont** [comment]
Le 05/03/2015 20:59, Michael Burman a écrit :
> There's in websocket branch this PR already: #163
> <https://github.com/hawkular/hawkular-metrics/pull/163> which does the
> same thing, but just quite a bit differently..

WDYM? I just had a look the PR, it creates a new Error class which 
replaces the usages of Map, but there's no ExceptionMapper to catch 
parsing problems, is there?

**Comment by tsegismont** [comment]
Rebased the PR on master.

Next (final) step: factor out an "entity created" callback.

**Comment by tsegismont** [comment]
Ready for review and merging.

**Comment by tsegismont** [comment]
@jsanda , @stefannegrea ok to merge?

**Comment by tsegismont** [comment]
Thanks John!

**Pull request merged**
