### PR TITLE
[HWKMETRICS-478] Protect /tenants endpoint with a secret admin token.

### PR DESCRIPTION
**Pull request by stefannegrea**
The token can be set or reset at startup via configuration property.

### CODE REVIEW

**Comment by burmanm** [comment]
@mwringe I'll need your input on this, as we'll need that /tenants endpoint in Heapster integration. So the token must be available to Heapster. And anything of course that requires fetching tenant information, such as Grafana integration..

**Comment by mwringe** [comment]
@stefannegrea does this affect standalone Hawkular Metrics? How does securing one endpoint really help things if everything else is wide open with respect to security?

**Comment by stefannegrea** [comment]
@burmanm, I would not use this token feature for Heapster, the TenantFilter should not be deployed on anywhere but Hawkular Metrics standalone.

**Comment by stefannegrea** [comment]
@mwringe, this is just the first PR in a series of PRs to add management features for Hawkular Metrics.

**Comment by mwringe** [comment]
@stefannegrea if this is going to be applied on top of a standalone Hawkular Metrics then it needs to be done as an optional filter so that we can continue to use the OpenShift filters without issues.

Or if we want to do this in a more proper fashion, we need to have a plugable security framework in place where we can use this implementation, the OpenShift one, or some other one.

**Comment by stefannegrea** [comment]
Based on the discussion with @mwringe, I will need to rework the tenant filter changes because it is used as-is by OpenShift at this time.

**Comment by mwringe** [comment]
With moving this to a separate filter, and having it disabled in the OpenShift case, I think this is better approach to take. LGTM

**Comment by stefannegrea** [comment]
retest this please

**Comment by jsanda** [comment]
> this is just the first PR in a series of PRs to add management features for Hawkular Metrics.

Do we have documented anywhere what we are planning to do next/long term in this area?

**Comment by stefannegrea** [comment]
@jsanda, we have the design document for the Management Framework. This is the first step in that area.

**Pull request merged**
