### PR TITLE
HWKMETRICS-104

### PR DESCRIPTION
**Pull request by mwringe**
Create a status endpoint to display the state of things such as the MetricsService.

WIP: do not merge yet.

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by pilhuhn** [comment]
/home/travis/build/hawkular/hawkular-metrics/api/metrics-api-jaxrs/src/main/java/org/hawkular/metrics/api/jaxrs/handler/StatusHandler.java:25:8: Unused import - javax.ws.rs.Consumes.

**Comment by pilhuhn** [comment]
Other than the above I think it looks good.

**Comment by mwringe** [comment]
I think it should be good to go if anyone wants to approve and merge.

**Comment by stefannegrea** [comment]
Thanks @mwringe

**Pull request merged**
