### PR TITLE
[HWKMETRICS-341] removing obsolete tenant creation code

### PR DESCRIPTION
**Pull request by jsanda**
If we decide that want to revisit I created https://github.com/jsanda/hawkular-metrics/tree/create-tenants for easy access and reference.

### CODE REVIEW

**Comment by jsanda** [comment]
My commit did not remove the tenants_by_time table from schema.cql. Since metrics has already been released in OpenShift, I want to be careful about non-additive schema changes. This should be done when we have a schema change management tool in place.

**Comment by tsegismont** [comment]
restest this please

**Comment by tsegismont** [comment]
retest this please

**Comment by tsegismont** [comment]
@jsanda @FilipB this PR improves the throughput by 15%. We need to talk about perfs before merging

**Comment by jsanda** [comment]
I was expecting some improvement, probably not as much as 15%, but some improvement nonetheless because there one less write being done on the execution path when inserting data points. Are there any concerns?

**Comment by tsegismont** [comment]
@jsanda I'm ok to merge but I think we need an approval for the resulting baseline change.

**Comment by jsanda** [comment]
@FilipB can you go ahead and reset the baseline?

**Comment by FilipB** [comment]
@jsanda @tsegismont Ready for merge

**Comment by tsegismont** [comment]
Perfect, thanks @FilipB !

**Pull request merged**
