### PR TITLE
some minor updates to run/test against C* 2.2.0

### PR DESCRIPTION
**Pull request by jsanda**
With this commit, everyone should be using Cassandra 2.2.0 in their local dev
environments.

In additon to having Travis use C* 2.2.0, I had to make some changes around
batch statements. When testing locally with a 2.2.0 cluster, I was getting some
failures about exceeding the batch_size_fail_threshold_in_kb setting defined
in cassandra.yaml. It defaults to 50 KB. BatchStatementTransformer had a check
on the number of statements in a batch. This is not really useful though
because the check needs to be on the overall size, not the number of statements
in the batch. I am going to create a ticket to address our usage of batch
statements. The conventional wisdom in general is to avoid them, and it makes
sense for adhere to that.

### CODE REVIEW

**Comment by tsegismont** [comment]
:-1: do not merge. You're cheating John :smile: 

First there's a test for each metric type which tries to send a lot of data points to check that insertion does not fail. These tests pass in Travis because:
- `checkArgument` call in `BatchStatementTransformer` is commented out
- the new MAX VALUE is much lower and so the generated batch does not exceed the internal kb size threshold

Also the `largeDataSetTest` passes because it now generates points for metrics at a much lower resolution.

In fact, the `BatchStatementTransformer#call` implementation changes are incorrect. We should emit enough `BatchStatement`s to insert all the data, not just one.

To accommodate to the C* 2.2 policy on batch bytes, you simply need to change `MAX_BATCH_SIZE` and leave the rest of the implementation.

**Comment by jsanda** [comment]
>First there's a test for each metric type which tries to send a lot of data points to check that insertion does not fail.

I am well aware of those tests. Not only does trying to insert batches with 65535 statements make little sense, but it is very bad idea. Those tests failed against Cassandra 2.2.0 because of exceeding ```batch_size_fail_threshold_in_kb```. What is the purpose or desire of trying to insert batches that large?  

>In fact, the BatchStatementTransformer#call implementation changes are incorrect. We should emit enough BatchStatements to insert all the data, not just one.

I disagree. The test was misleading because the only place the ```BatchStatementTransformer(Func0<BatchStatement> batchStatementFactory, int batchSize)``` constructor was used was in the unit test which means everywhere BatchStatementTransformer is used in production code we are only generating a single batch statement.

>To accommodate to the C* 2.2 policy on batch bytes, you simply need to change MAX_BATCH_SIZE and leave the rest of the implementation.

As I mentioned in the commit log, I am going to open another ticket to altogether avoid batch statements.  The conventional thinking suggests avoiding unlogged batches, and it makes sense. Atomic batches are different, but we do not use them anywhere.

**Comment by tsegismont** [comment]
Le 27/08/2015 22:34, jsanda a écrit :
>     First there's a test for each metric type which tries to send a lot
>     of data points to check that insertion does not fail.
>
> I am well aware of those tests. Not only does trying to insert batches
> with 65535 statements make little sense, but it is very bad idea. Those
> tests failed against Cassandra 2.2.0 because of exceeding
> |batch_size_fail_threshold_in_kb|. What is the purpose or desire of
> trying to insert batches that large?

Those tests don't verify you can create large C* batches, they verify 
you can send a payload of arbitrary size to the Metrics REST interface.

It happens that the current implementation of BatchStatementTransformer 
does that in 1 batch if the number of data points is lower than the 
maximum batch count.

>
>     In fact, the BatchStatementTransformer#call implementation changes
>     are incorrect. We should emit enough BatchStatements to insert all
>     the data, not just one.
>
> I disagree. The test was misleading because the only place the
> |BatchStatementTransformer(Func0<BatchStatement> batchStatementFactory,
> int batchSize)| constructor was used was in the unit test which means
> everywhere BatchStatementTransformer is used in production code we are
> only generating a single batch statement.

We're generating a single batch statement in production code if the 
number of data points to insert is lower than the maximum size.

With the perf tests I did today on #window vs #groupBy, I did send a lot 
of POST requests with large payloads, and I can tell you they'd have 
fail if a single batch statement had been emitted.

>
>     To accommodate to the C* 2.2 policy on batch bytes, you simply need
>     to change MAX_BATCH_SIZE and leave the rest of the implementation.
>
> As I mentioned in the commit log, I am going to open another ticket to
> altogether avoid batch statements. The conventional thinking suggests
> avoiding unlogged batches, and it makes sense. Atomic batches are
> different, but we do not use them anywhere.

Yes, I saw it. I'm fine with experimenting insertion without batches, 
but that's not the issue here. The issue is that if we merge this PR, we 
can't send POST requests with more than 1024 data points anymore.

**Comment by jsanda** [comment]
We do one insert into the data table per data point. This change does not restrict the REST API. The check on the batch size is commented out.

**Comment by tsegismont** [comment]
> We do one insert into the data table per data point.

In master, if the number of data points in the request body is bigger than the maximum allowed, we emit multiple `BatchStatement` and then `flatMap` on `rxSession.execute`. So all inserts are executed.

With your changes, we create one big `BatchStatement` which fails to be executed. As mentioned in an earlier comment, Travis marks this PR green because the test code was changed to send a few points, thus hiding the issue.

If you have any doubt, apply this patch to your branch.

```diff
Index: rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy	(date 1440698253000)
+++ rest-tests/src/test/groovy/org/hawkular/metrics/rest/RESTTest.groovy	(revision )
@@ -15,15 +15,19 @@
  * limitations under the License.
  */
 package org.hawkular.metrics.rest
-import com.google.common.base.Charsets
-import groovyx.net.http.ContentType
-import groovyx.net.http.RESTClient
+
+import static org.junit.Assert.assertEquals
+
+import java.util.concurrent.atomic.AtomicInteger
+
+import org.hawkular.metrics.core.impl.transformers.BatchStatementTransformer
 import org.joda.time.DateTime
 import org.junit.BeforeClass
 
-import java.util.concurrent.atomic.AtomicInteger
+import com.google.common.base.Charsets
 
-import static org.junit.Assert.assertEquals
+import groovyx.net.http.ContentType
+import groovyx.net.http.RESTClient
 
 class RESTTest {
 
@@ -31,7 +35,7 @@
   static final double DELTA = 0.001
   static final String TENANT_PREFIX = UUID.randomUUID().toString()
   static final AtomicInteger TENANT_ID_COUNTER = new AtomicInteger(0)
-  static final int LARGE_PAYLOAD_SIZE = 1024
+  static final int LARGE_PAYLOAD_SIZE = 0xFFFF
   static String tenantHeaderName = "Hawkular-Tenant";
   static RESTClient hawkularMetrics
   static defaultFailureHandler
Index: rest-tests/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- rest-tests/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy	(date 1440698253000)
+++ rest-tests/src/test/groovy/org/hawkular/metrics/rest/GaugeMetricStatisticsITest.groovy	(revision )
@@ -161,7 +161,7 @@
     String metric = "test"
     int nbOfBuckets = 10
     long bucketSize = Duration.standardDays(1).millis
-    int interval = Duration.standardMinutes(10).millis
+    int interval = Duration.standardSeconds(30).millis
     int sampleSize = (bucketSize / interval) - 1
 
     def start = new DateTimeService().currentHour().minus(3 * nbOfBuckets * bucketSize)
```

Then the tests we talked about will fail like this:
```
Got error response: HTTP/1.1 500 Internal Server Error
=== Response body
{"errorMsg":"Failed to perform operation due to an error: OnError while emitting onNext value: com.datastax.driver.core.BoundStatement.class"}
===
```

And if you have trace level logging on your server for the `org.hawkular.metrics.api.jaxrs.util.ApiUtils` category, you'll see this exception logged:
```
10:21:31,796 TRACE [org.hawkular.metrics.api.jaxrs.util.ApiUtils] (default task-32) Server error response: java.lang.IllegalStateException: Batch statement cannot contain more than 65535 statements.
	at com.datastax.driver.core.BatchStatement.add(BatchStatement.java:143)
	at org.hawkular.metrics.core.impl.transformers.BatchStatementTransformer$$Lambda$53/1410899486.call(Unknown Source)
	at rx.Observable$4.call(Observable.java:3685)
	at rx.internal.operators.OperatorScan$2.onNext(OperatorScan.java:105)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:79)
	at rx.internal.operators.OperatorScan$2$1.request(OperatorScan.java:151)
	at rx.Subscriber.setProducer(Subscriber.java:209)
	at rx.internal.operators.OperatorScan$2.setProducer(OperatorScan.java:141)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7713)
	at rx.internal.util.ScalarSynchronousObservable$2.call(ScalarSynchronousObservable.java:133)
	at rx.internal.util.ScalarSynchronousObservable$2.call(ScalarSynchronousObservable.java:125)
	at rx.Observable.unsafeSubscribe(Observable.java:7713)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:140)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:106)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.subscribe(Observable.java:7803)
	at rx.Observable.subscribe(Observable.java:7634)
	at org.hawkular.metrics.core.impl.MetricsServiceImpl.addGaugeData(MetricsServiceImpl.java:580)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.jboss.weld.proxies.MetricsService$54238400$Proxy$_$$_WeldClientProxy.addGaugeData(Unknown Source)
	at org.hawkular.metrics.api.jaxrs.handler.GaugeHandler.addDataForMetric(GaugeHandler.java:202)
	at org.hawkular.metrics.api.jaxrs.handler.GaugeHandler$Proxy$_$$_WeldClientProxy.addDataForMetric(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.datastax.driver.core.BoundStatement.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:104)
	at rx.internal.operators.OperatorScan$2.onNext(OperatorScan.java:108)
	... 85 more
```

The part of this PR which relates to batch handling causes a regression, to the state we were in before [HWKMETRICS-215](https://issues.jboss.org/browse/HWKMETRICS-215) was fixed. See PR #309.

I'm not opposed to drop usage of `BatchStatement` in any way. But as you say, it deserves a separate ticket+PR.

The goal of this PR is to make Travis run C* 2.2.x instead of 2.1.x. So I suggest we simply adjust the `MAX_BATCH_SIZE` constant.

**Comment by tsegismont** [comment]
Thanks John!

**Pull request merged**
