### PR TITLE
HWKMETRICS-121 Reduce the amount of details logged at INFO level

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by ppalaga** [comment]
@jsanda could you please review and eventually merge?

**Comment by tsegismont** [comment]
:+1:

**Pull request merged**
