### PR TITLE
Updated Accounts to 2.0.21.Final

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by ppalaga** [comment]
@jpkrohling sent https://github.com/jpkrohling/hawkular-metrics/pull/1 against your branch

**Comment by jpkrohling** [comment]
PR merged, but how does it work? Should we wait for #445 to be merged, or would a merge of this PR close #445 as well?

**Comment by ppalaga** [comment]
> PR merged, but how does it work? Should we wait for #445 to be merged, or would a merge of this PR close #445 as well?

see https://github.com/hawkular/hawkular-metrics/pull/445#issuecomment-183338204

**Comment by stefannegrea** [comment]
Thanks @tsegismont, @jpkrohling, @ppalaga!

**Pull request merged**
