### PR TITLE
HWKMETRICS-636 Move release/0.23.0 to Alerting fix version 1.5.4.Final

### PR DESCRIPTION
**Pull request by jshaughn**

### CODE REVIEW

**Comment by jshaughn** [comment]
retest this please

**Comment by jshaughn** [comment]
@stefannegrea I can't explain the perf failures. I don't see how it can be related.

**Comment by FilipB** [comment]
@jshaughn @stefannegrea the performance drop is visible because the baselines for release/0.23.0 and master have diverged and the check only uses baselines for master. In other words master is faster than release/0.23.0

**Comment by stefannegrea** [comment]
Will merge the PR as-is based on the comments from @FilipB.

**Pull request merged**
