### PR TITLE
HWKMETRICS-215 IllegalStateException: Batch statement cannot contain more than 65535 statements

### PR DESCRIPTION
**Pull request by tsegismont**
C* batch size is limited to 0xFFFF. This fix lets the user submit a payload of arbitrary size.

### CODE REVIEW

**Comment by tsegismont** [comment]
I just pushed a commit to extract a `BatchStatementTransformer` class so that it can be re-used. I guess we should pay attention to that everywhere we use BatchStatement.

**Comment by jsanda** [comment]
I think the changes look good. While you are at it, could you also refactor ```DataAccessImpl.updateMetricsIndexRx``` to use the batch transformer.

**Comment by tsegismont** [comment]
I'm doing this right now :) In fact, I'm also doing it everywhere it makes sense.

**Comment by tsegismont** [comment]
@jsanda done. Ready for final review.

I've also added a trivial regression test for the batcher and removed the unused, Futures-based `DataAccessImpl#updateMetricsIndex` method.

**Comment by jsanda** [comment]
retest this please

**Pull request merged**
