### PR TITLE
Upgrade to hawkular-parent 15 see https://github.com/hawkular/hawkular-parent-pom/commits/15

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by tsegismont** [comment]
Merged, thanks @ppalaga

**Comment by ppalaga** [comment]
@tsegismont is CI not failing?

**Comment by ppalaga** [comment]
@tsegismont ah, looking at the details, the two Jenkins jobs use Maven central only. Therefore their failures are expected and an clearly explicable.

**Comment by tsegismont** [comment]
@ppalaga Travis is happy and that's enough for me

**Pull request merged**
