### PR TITLE
[HWKMETRICS-526] report status of Cassandra nodes

### PR DESCRIPTION
**Pull request by jsanda**
The output of the status endpoint now looks like:

```json
{
  "MetricsService": "STARTED", 
  "Built-From-Git-SHA": "291fabc1214149653ee3df14e0f2c60b10c64360", 
  "Implementation-Version": "0.22.0-SNAPSHOT", 
  "Cassandra": [
    {
      "address": "127.0.0.1", 
      "status": "up"
    }, 
    {
      "address": "127.0.0.2", 
      "status": "up"
    }, 
    {
        "address": "127.0.0.3",
        "status": "up"
    }
  ]
}
```

@mwringe does this work for you?

### CODE REVIEW

**Comment by mwringe** [comment]
Do we want to expose the ip address of the nodes? The status endpoint currently is public and I don't know if we want the ip address of the Cassandra nodes should be considered more private information.

**Comment by jsanda** [comment]
If a node is down, we won't be able to see which one is down without including the addresses. What is the security concern/risk with exposes the addresses?

**Comment by stefannegrea** [comment]
@jsanda, exposing the information about the infrastructure is always a security concern. For example, it allows an attacker to estimate the resources needed for a successful DDoS attack.

@jsanda, @mwringe, how about a separate protected admin status endpoint (`admin/status`) that contains the existing status info plus change proposed in this PR. Later we could expand the admin status to container other sensitive information such as WF topology.

**Comment by mwringe** [comment]
A separate /admin/status endpoint would work here

**Comment by jsanda** [comment]
What do we want to for the existing status endpoint with respect to Cassandra? Here is one idea if we still want to include Cassandra info on the existing status endpoint. If all nodes are up, we report up. If all nodes are down we report down. If some nodes are down we report something like partially up. Thoughts?

**Comment by stefannegrea** [comment]
If some nodes are down, it is possible the cluster is  operational but have reduced performance or not operational at all. @jsanda, how about calling the third state `degraded`?

**Comment by jsanda** [comment]
> If some nodes are down, it is possible the cluster is operational but have reduced performance or not operational at all. 

The cluster is still operational, but some requests will fail. If we have nodes A, B, and C with RF = 1, then each node owns roughly 33.3% of keys. If node B goes down, requests targeted for B will fail, but requests targeted for A and C will succeed.

> how about calling the third state degraded?

Works for me.

**Comment by stefannegrea** [comment]
Thanks @jsanda!

**Pull request merged**
