### PR TITLE
Replace srcdeps-maven-plugin with srcdeps core extension

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jsanda or @stefannegrea could you please review?

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
Please ping me before merging, this approach requires changes in our CI

**Comment by ppalaga** [comment]
> Please ping me before merging, this approach requires changes in our CI

@FilipB probably wants to say that he knows how the haw-metrics-perf-stability-test Jenkins job can be fixed and he thus approves this PR.

**Comment by ppalaga** [comment]
I have just rebased on top of the current master and solved the conflict.

**Comment by stefannegrea** [comment]
Thank you @ppalaga!

**Pull request merged**
