### PR TITLE
HWKMETRICS-37 collectd/ptrans/metrics full stack integration test

### PR DESCRIPTION
**Pull request by tsegismont**
This is a PR to run an end to end regression test on Travis (collectd, ptrans, hawkular-metrics)

Not ready for merge, initial work only.

### CODE REVIEW

**Comment by tsegismont** [comment]
The last build failure is expected: it means that collectd was successfully installed on Travis and jUnit assumptions were verified. The main test method only has one line now: `fail("Not implemented yet")`

**Comment by tsegismont** [comment]
Now pTrans is started, then collectd is started, and collectd is configured to output sent measurements to stdout.

Next steps:
- parse collectd stdout to produce an "expected" data set
- query metrics REST API to get an "actual" data set
- compare

**Comment by tsegismont** [comment]
We'll what Travis says but this "fullstack" test now works on my box:
collectd -> ptrans ->metrics

Next steps (if Travis is happy):
* rebase on master
* speed up the test (if possible)

**Comment by tsegismont** [comment]
Rebased on master. It could be merged as is. But the test currently takes 18secs (because collectd csv plugin takes some time before logging values).

**Comment by tsegismont** [comment]
Rebased on master again. Also, I've updated `collectd.conf` file, as it worked on my machine but not on Travis (collectd 5.x vs 4.x)

**Comment by tsegismont** [comment]
@stefannegrea @jsanda I've struggled to get it done and work nicely in different envs (Travis, dev box w/ or w/o collectd), but it's ready now.

Could one of you please review and merge? Thanks

**Comment by stefannegrea** [comment]
Forcing retest with Jenkins.

**Comment by tsegismont** [comment]
What?

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
Thanks @tsegismont!

**Pull request merged**
