### PR TITLE
[HWKMETRICS-518] make sure activeTimeSlices cache is updated when error occurs

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
retest this please

**Comment by FilipB** [comment]
@jsanda Metrics were not started with following error in server.log:
2016-10-24 23:53:34,605 FATAL [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200006: An error occurred trying to connect to the Cassandra cluster: groovy.lang.MissingMethodException: No signature of method: org.cassalog.core.CqlChangeSet.verify() is applicable for argument types: (schema-0_15_0$_run_closure1$_closure6) values: [schema-0_15_0$_run_closure1$_closure6@4ea5b27]
Possible solutions: notify(), every(), version(java.lang.Object), every(groovy.lang.Closure), grep(), print(java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
.
.
at org.hawkular.schema.cassalog.run(cassalog.groovy:23)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:641)
	at groovy.lang.GroovyShell$evaluate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.cassalog.core.CassalogImpl.execute(CassalogImpl.groovy:75)
	at org.hawkular.metrics.schema.SchemaService.run(SchemaService.java:60)
	at org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.initSchema(MetricsServiceLifecycle.java:409)
	at org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.startMetricsService(MetricsServiceLifecycle.java:274)


This is probably not related to this PR since I noticed this exception in other PR as well

**Comment by jsanda** [comment]
retest this please

**Comment by FilipB** [comment]
@jsanda please ignore error from my previous comment. It was caused by env issue.

**Comment by jsanda** [comment]
I just added the DO NOT MERGE label because I want to test some more to make sure the changes are stable. So far everything looks good. I have had a server running for almost 24 hours without any errors.

**Comment by jsanda** [comment]
This is ready for review/merge.

**Comment by jsanda** [comment]
retest this please

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Pull request merged**
