### PR TITLE
add back the mixed metrics endpoint with support for…

### PR DESCRIPTION
**Pull request by jsanda**
… counters

### CODE REVIEW

**Comment by jsanda** [comment]
There is one thing lacking. If the request fails, we do not provide any info to the client as to what failed. For example, maybe only the insertion of counters failed. Providing more info on the failure would allow the client to then only resubmit the counter data. We need this and other error handling in a lot of other places; so, I am ok without doing it in this PR.

**Comment by burmanm** [comment]
The error handling is one part of the issue, the second part is the usefulness of this feature. See the JIRA for discussion.

**Comment by tsegismont** [comment]
Le 03/07/2015 22:50, jsanda a écrit :
> I am ok without doing it in this PR

+1

It's a larger problem which should be discussed elsewhere than in this PR.

**Comment by stefannegrea** [comment]
I opened [HWKMETRICS-170](https://issues.jboss.org/browse/HWKMETRICS-170) to track error reporting as mentioned in @jsanda comment.

**Comment by stefannegrea** [comment]
Since the endpoint is currently in use by multiple clients, this PR makes sense since it is just a fix to support the recently enhanced counter metrics.

**Comment by burmanm** [comment]
Actually it's not in use in any client (it was disabled in the 0.3.4 and hasn't been enabled since - it's not working in 0.3.4 or 0.4.0)

**Comment by pilhuhn** [comment]
@stefannegrea In Hawkular we had to work around in a few places, as this endpoint all of a sudden ceased to work correctly. It returned a 200 OK, but internally was a NO-OP.

I see value in this endpoint, because it allows to send more data in a batch. But then I recently did work to support Http2, which does connection pooling/multiplexing and thus potentially reduces the need to do such batching client side.

**Comment by tsegismont** [comment]
@pilhuhn http2 could certainly help, when the client is able to upgrade the connection.

There were two things discussed in the JIRA:
* is the mixed post endpoint needed/useful?
* which format should be used?

I think the first one has been answered already: the endpoint is needed.

The second one has not really been answered. I am in favor of keeping the current format, which groups data points by metric type:
```json
{
  "counters": [
    {
      "id": "counter1",
      "data": [
        {
          "timestamp": 1, 
          "value": 1
        }
      ] 
    } 
  ], 
  "gauges": [
    {
      "id": "gauge0",
      "data": [
        {
          "timestamp": 0, 
          "value": 0.0
        }
      ]
    } 
  ], 
  "availabilities": [
    {
      "id": "avail2",
      "data": [
        {
          "timestamp": 2, 
          "value": "up"
        }
      ]
    } 
  ]
}
```
Because to me, data point is meta-data, and does not need to be repeated.

I've written a little test class to compare the size of the payload when sending batches of different lengths.

```java
import static java.util.stream.Collectors.groupingBy;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toList;

import static org.hawkular.metrics.core.api.AvailabilityType.DOWN;
import static org.hawkular.metrics.core.api.AvailabilityType.UP;
import static org.hawkular.metrics.core.api.MetricType.AVAILABILITY;
import static org.hawkular.metrics.core.api.MetricType.COUNTER;
import static org.hawkular.metrics.core.api.MetricType.GAUGE;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.List;
import java.util.Map;
import java.util.stream.IntStream;

import org.hawkular.metrics.core.api.DataPoint;
import org.hawkular.metrics.core.api.Metric;
import org.hawkular.metrics.core.api.MetricId;
import org.hawkular.metrics.core.api.MetricType;

public class JsonCompare {

    public static void main(String[] args) {
        System.out.println(IntStream.range(0, 10)
                .map(i -> (i + 1) * 10)
                .mapToObj(JsonCompare::printResults)
                .collect(joining("\n\n")));
    }

    private static String printResults(int count) {
        StringWriter stringWriter = new StringWriter();
        PrintWriter printWriter = new PrintWriter(stringWriter);

        printWriter.println("count = " + count);

        List<Metric> metrics = IntStream.range(0, count)
                .mapToObj(JsonCompare::toMetric)
                .collect(toList());

        String standard = "[" + metrics.stream()
                .map(JsonCompare::toStandardJson)
                .collect(joining(",")) + "]";
        printWriter.println(standard);
        int standardLength = standard.getBytes().length;
        printWriter.println(standardLength);

        Map<MetricType, List<Metric>> grouped = metrics.stream().collect(groupingBy(Metric::getType));
        String gauge = "\"gauges\":[" + grouped.get(GAUGE).stream()
                .map(JsonCompare::toOptimizedJson)
                .collect(joining(",")) + "]";
        String counter = "\"counters\":[" + grouped.get(COUNTER).stream()
                .map(JsonCompare::toOptimizedJson)
                .collect(joining(",")) + "]";
        String avail = "\"availabilities\":[" + grouped.get(AVAILABILITY).stream()
                .map(JsonCompare::toOptimizedJson)
                .collect(joining(",")) + "]";
        String optimized = "{" + gauge + "," + counter + "," + avail + "}";
        printWriter.println(optimized);
        int optimizedLength = optimized.getBytes().length;
        printWriter.println(optimizedLength);

        printWriter.println("gain = " + 100 * ((double) standardLength - optimizedLength) / standardLength);

        printWriter.close();
        return stringWriter.toString();
    }

    private static String toStandardJson(Metric<?> m) {
        DataPoint<?> dataPoint = m.getDataPoints().get(0);
        Object value = dataPoint.getValue();
        if (value instanceof String) {
            value = "\"" + value + "\"";
        }
        return String.format("{\"id\":\"%s\",\"data\":[{\"timestamp\":%s,\"value\":%s,\"type\":\"%s\"}]}",
                m.getId().getName(), dataPoint.getTimestamp(), value, m.getType());
    }

    private static String toOptimizedJson(Metric<?> m) {
        DataPoint<?> dataPoint = m.getDataPoints().get(0);
        Object value = dataPoint.getValue();
        if (value instanceof String) {
            value = "\"" + value + "\"";
        }
        return String.format("{\"id\":\"%s\",\"data\":[{\"timestamp\":%s,\"value\":%s}]}",
                m.getId().getName(), dataPoint.getTimestamp(), value);
    }

    private static Metric toMetric(int i) {
        if (i % 3 == 0) {
            Metric<Double> gauge = new Metric<>("tenant", GAUGE, new MetricId("gauge" + i));
            gauge.getDataPoints().add(new DataPoint<>(i, (double) i));
            return gauge;
        }
        if (i % 3 == 1) {
            Metric<Long> counter = new Metric<>("tenant", COUNTER, new MetricId("counter" + i));
            counter.getDataPoints().add(new DataPoint<>(i, (long) i));
            return counter;
        }
        Metric<String> avail = new Metric<>("tenant", AVAILABILITY, new MetricId("avail" + i));
        avail.getDataPoints().add(new DataPoint<>(i, i % 2 == 0 ? UP.getText() : DOWN.getText()));
        return avail;
    }

}
```

Here's a summary of the results:

```
count = 10
[{"id":"gauge0","data":[{"timestamp":0,"value":0.0,"type":"gauge"}]},{"id":"counter1","data":[{"timestamp":1,"value":1,"type":"counter"}]},{"id":"avail2","data":[{"timestamp":2,"value":"up","type":"availability"}]},{"id":"gauge3","data":[{"timestamp":3,"value":3.0,"type":"gauge"}]},{"id":"counter4","data":[{"timestamp":4,"value":4,"type":"counter"}]},{"id":"avail5","data":[{"timestamp":5,"value":"down","type":"availability"}]},{"id":"gauge6","data":[{"timestamp":6,"value":6.0,"type":"gauge"}]},{"id":"counter7","data":[{"timestamp":7,"value":7,"type":"counter"}]},{"id":"avail8","data":[{"timestamp":8,"value":"up","type":"availability"}]},{"id":"gauge9","data":[{"timestamp":9,"value":9.0,"type":"gauge"}]}]
713
{"gauges":[{"id":"gauge0","data":[{"timestamp":0,"value":0.0}]},{"id":"gauge3","data":[{"timestamp":3,"value":3.0}]},{"id":"gauge6","data":[{"timestamp":6,"value":6.0}]},{"id":"gauge9","data":[{"timestamp":9,"value":9.0}]}],"counters":[{"id":"counter1","data":[{"timestamp":1,"value":1}]},{"id":"counter4","data":[{"timestamp":4,"value":4}]},{"id":"counter7","data":[{"timestamp":7,"value":7}]}],"availabilities":[{"id":"avail2","data":[{"timestamp":2,"value":"up"}]},{"id":"avail5","data":[{"timestamp":5,"value":"down"}]},{"id":"avail8","data":[{"timestamp":8,"value":"up"}]}]}
579
gain = 18.79382889200561

...

count = 100
[{"id":"gauge0","data":[{"timestamp":0,"value":0.0,"type":"gauge"}]},{"id":"counter1","data":[{"timestamp":1,"value":1,"type":"counter"}]},{"id":"avail2","data":[{"timestamp":2,"value":"up","type":"availability"}]},{"id":"gauge3","data":[{"timestamp":3,"value":3.0,"type":"gauge"}]},{"id":"counter4","data":[{"timestamp":4,"value":4,"type":"counter"}]},{"id":"avail5","data":[{"timestamp":5,"value":"down","type":"availability"}]},{"id":"gauge6","data":[{"timestamp":6,"value":6.0,"type":"gauge"}]},{"id":"counter7","data":[{"timestamp":7,"value":7,"type":"counter"}]},{"id":"avail8","data":[{"timestamp":8,"value":"up","type":"availability"}]},{"id":"gauge9","data":[{"timestamp":9,"value":9.0,"type":"gauge"}]},{"id":"counter10","data":[{"timestamp":10,"value":10,"type":"counter"}]},{"id":"avail11","data":[{"timestamp":11,"value":"down","type":"availability"}]},{"id":"gauge12","data":[{"timestamp":12,"value":12.0,"type":"gauge"}]},{"id":"counter13","data":[{"timestamp":13,"value":13,"type":"counter"}]},{"id":"avail14","data":[{"timestamp":14,"value":"up","type":"availability"}]},{"id":"gauge15","data":[{"timestamp":15,"value":15.0,"type":"gauge"}]},{"id":"counter16","data":[{"timestamp":16,"value":16,"type":"counter"}]},{"id":"avail17","data":[{"timestamp":17,"value":"down","type":"availability"}]},{"id":"gauge18","data":[{"timestamp":18,"value":18.0,"type":"gauge"}]},{"id":"counter19","data":[{"timestamp":19,"value":19,"type":"counter"}]},{"id":"avail20","data":[{"timestamp":20,"value":"up","type":"availability"}]},{"id":"gauge21","data":[{"timestamp":21,"value":21.0,"type":"gauge"}]},{"id":"counter22","data":[{"timestamp":22,"value":22,"type":"counter"}]},{"id":"avail23","data":[{"timestamp":23,"value":"down","type":"availability"}]},{"id":"gauge24","data":[{"timestamp":24,"value":24.0,"type":"gauge"}]},{"id":"counter25","data":[{"timestamp":25,"value":25,"type":"counter"}]},{"id":"avail26","data":[{"timestamp":26,"value":"up","type":"availability"}]},{"id":"gauge27","data":[{"timestamp":27,"value":27.0,"type":"gauge"}]},{"id":"counter28","data":[{"timestamp":28,"value":28,"type":"counter"}]},{"id":"avail29","data":[{"timestamp":29,"value":"down","type":"availability"}]},{"id":"gauge30","data":[{"timestamp":30,"value":30.0,"type":"gauge"}]},{"id":"counter31","data":[{"timestamp":31,"value":31,"type":"counter"}]},{"id":"avail32","data":[{"timestamp":32,"value":"up","type":"availability"}]},{"id":"gauge33","data":[{"timestamp":33,"value":33.0,"type":"gauge"}]},{"id":"counter34","data":[{"timestamp":34,"value":34,"type":"counter"}]},{"id":"avail35","data":[{"timestamp":35,"value":"down","type":"availability"}]},{"id":"gauge36","data":[{"timestamp":36,"value":36.0,"type":"gauge"}]},{"id":"counter37","data":[{"timestamp":37,"value":37,"type":"counter"}]},{"id":"avail38","data":[{"timestamp":38,"value":"up","type":"availability"}]},{"id":"gauge39","data":[{"timestamp":39,"value":39.0,"type":"gauge"}]},{"id":"counter40","data":[{"timestamp":40,"value":40,"type":"counter"}]},{"id":"avail41","data":[{"timestamp":41,"value":"down","type":"availability"}]},{"id":"gauge42","data":[{"timestamp":42,"value":42.0,"type":"gauge"}]},{"id":"counter43","data":[{"timestamp":43,"value":43,"type":"counter"}]},{"id":"avail44","data":[{"timestamp":44,"value":"up","type":"availability"}]},{"id":"gauge45","data":[{"timestamp":45,"value":45.0,"type":"gauge"}]},{"id":"counter46","data":[{"timestamp":46,"value":46,"type":"counter"}]},{"id":"avail47","data":[{"timestamp":47,"value":"down","type":"availability"}]},{"id":"gauge48","data":[{"timestamp":48,"value":48.0,"type":"gauge"}]},{"id":"counter49","data":[{"timestamp":49,"value":49,"type":"counter"}]},{"id":"avail50","data":[{"timestamp":50,"value":"up","type":"availability"}]},{"id":"gauge51","data":[{"timestamp":51,"value":51.0,"type":"gauge"}]},{"id":"counter52","data":[{"timestamp":52,"value":52,"type":"counter"}]},{"id":"avail53","data":[{"timestamp":53,"value":"down","type":"availability"}]},{"id":"gauge54","data":[{"timestamp":54,"value":54.0,"type":"gauge"}]},{"id":"counter55","data":[{"timestamp":55,"value":55,"type":"counter"}]},{"id":"avail56","data":[{"timestamp":56,"value":"up","type":"availability"}]},{"id":"gauge57","data":[{"timestamp":57,"value":57.0,"type":"gauge"}]},{"id":"counter58","data":[{"timestamp":58,"value":58,"type":"counter"}]},{"id":"avail59","data":[{"timestamp":59,"value":"down","type":"availability"}]},{"id":"gauge60","data":[{"timestamp":60,"value":60.0,"type":"gauge"}]},{"id":"counter61","data":[{"timestamp":61,"value":61,"type":"counter"}]},{"id":"avail62","data":[{"timestamp":62,"value":"up","type":"availability"}]},{"id":"gauge63","data":[{"timestamp":63,"value":63.0,"type":"gauge"}]},{"id":"counter64","data":[{"timestamp":64,"value":64,"type":"counter"}]},{"id":"avail65","data":[{"timestamp":65,"value":"down","type":"availability"}]},{"id":"gauge66","data":[{"timestamp":66,"value":66.0,"type":"gauge"}]},{"id":"counter67","data":[{"timestamp":67,"value":67,"type":"counter"}]},{"id":"avail68","data":[{"timestamp":68,"value":"up","type":"availability"}]},{"id":"gauge69","data":[{"timestamp":69,"value":69.0,"type":"gauge"}]},{"id":"counter70","data":[{"timestamp":70,"value":70,"type":"counter"}]},{"id":"avail71","data":[{"timestamp":71,"value":"down","type":"availability"}]},{"id":"gauge72","data":[{"timestamp":72,"value":72.0,"type":"gauge"}]},{"id":"counter73","data":[{"timestamp":73,"value":73,"type":"counter"}]},{"id":"avail74","data":[{"timestamp":74,"value":"up","type":"availability"}]},{"id":"gauge75","data":[{"timestamp":75,"value":75.0,"type":"gauge"}]},{"id":"counter76","data":[{"timestamp":76,"value":76,"type":"counter"}]},{"id":"avail77","data":[{"timestamp":77,"value":"down","type":"availability"}]},{"id":"gauge78","data":[{"timestamp":78,"value":78.0,"type":"gauge"}]},{"id":"counter79","data":[{"timestamp":79,"value":79,"type":"counter"}]},{"id":"avail80","data":[{"timestamp":80,"value":"up","type":"availability"}]},{"id":"gauge81","data":[{"timestamp":81,"value":81.0,"type":"gauge"}]},{"id":"counter82","data":[{"timestamp":82,"value":82,"type":"counter"}]},{"id":"avail83","data":[{"timestamp":83,"value":"down","type":"availability"}]},{"id":"gauge84","data":[{"timestamp":84,"value":84.0,"type":"gauge"}]},{"id":"counter85","data":[{"timestamp":85,"value":85,"type":"counter"}]},{"id":"avail86","data":[{"timestamp":86,"value":"up","type":"availability"}]},{"id":"gauge87","data":[{"timestamp":87,"value":87.0,"type":"gauge"}]},{"id":"counter88","data":[{"timestamp":88,"value":88,"type":"counter"}]},{"id":"avail89","data":[{"timestamp":89,"value":"down","type":"availability"}]},{"id":"gauge90","data":[{"timestamp":90,"value":90.0,"type":"gauge"}]},{"id":"counter91","data":[{"timestamp":91,"value":91,"type":"counter"}]},{"id":"avail92","data":[{"timestamp":92,"value":"up","type":"availability"}]},{"id":"gauge93","data":[{"timestamp":93,"value":93.0,"type":"gauge"}]},{"id":"counter94","data":[{"timestamp":94,"value":94,"type":"counter"}]},{"id":"avail95","data":[{"timestamp":95,"value":"down","type":"availability"}]},{"id":"gauge96","data":[{"timestamp":96,"value":96.0,"type":"gauge"}]},{"id":"counter97","data":[{"timestamp":97,"value":97,"type":"counter"}]},{"id":"avail98","data":[{"timestamp":98,"value":"up","type":"availability"}]},{"id":"gauge99","data":[{"timestamp":99,"value":99.0,"type":"gauge"}]}]
7403
{"gauges":[{"id":"gauge0","data":[{"timestamp":0,"value":0.0}]},{"id":"gauge3","data":[{"timestamp":3,"value":3.0}]},{"id":"gauge6","data":[{"timestamp":6,"value":6.0}]},{"id":"gauge9","data":[{"timestamp":9,"value":9.0}]},{"id":"gauge12","data":[{"timestamp":12,"value":12.0}]},{"id":"gauge15","data":[{"timestamp":15,"value":15.0}]},{"id":"gauge18","data":[{"timestamp":18,"value":18.0}]},{"id":"gauge21","data":[{"timestamp":21,"value":21.0}]},{"id":"gauge24","data":[{"timestamp":24,"value":24.0}]},{"id":"gauge27","data":[{"timestamp":27,"value":27.0}]},{"id":"gauge30","data":[{"timestamp":30,"value":30.0}]},{"id":"gauge33","data":[{"timestamp":33,"value":33.0}]},{"id":"gauge36","data":[{"timestamp":36,"value":36.0}]},{"id":"gauge39","data":[{"timestamp":39,"value":39.0}]},{"id":"gauge42","data":[{"timestamp":42,"value":42.0}]},{"id":"gauge45","data":[{"timestamp":45,"value":45.0}]},{"id":"gauge48","data":[{"timestamp":48,"value":48.0}]},{"id":"gauge51","data":[{"timestamp":51,"value":51.0}]},{"id":"gauge54","data":[{"timestamp":54,"value":54.0}]},{"id":"gauge57","data":[{"timestamp":57,"value":57.0}]},{"id":"gauge60","data":[{"timestamp":60,"value":60.0}]},{"id":"gauge63","data":[{"timestamp":63,"value":63.0}]},{"id":"gauge66","data":[{"timestamp":66,"value":66.0}]},{"id":"gauge69","data":[{"timestamp":69,"value":69.0}]},{"id":"gauge72","data":[{"timestamp":72,"value":72.0}]},{"id":"gauge75","data":[{"timestamp":75,"value":75.0}]},{"id":"gauge78","data":[{"timestamp":78,"value":78.0}]},{"id":"gauge81","data":[{"timestamp":81,"value":81.0}]},{"id":"gauge84","data":[{"timestamp":84,"value":84.0}]},{"id":"gauge87","data":[{"timestamp":87,"value":87.0}]},{"id":"gauge90","data":[{"timestamp":90,"value":90.0}]},{"id":"gauge93","data":[{"timestamp":93,"value":93.0}]},{"id":"gauge96","data":[{"timestamp":96,"value":96.0}]},{"id":"gauge99","data":[{"timestamp":99,"value":99.0}]}],"counters":[{"id":"counter1","data":[{"timestamp":1,"value":1}]},{"id":"counter4","data":[{"timestamp":4,"value":4}]},{"id":"counter7","data":[{"timestamp":7,"value":7}]},{"id":"counter10","data":[{"timestamp":10,"value":10}]},{"id":"counter13","data":[{"timestamp":13,"value":13}]},{"id":"counter16","data":[{"timestamp":16,"value":16}]},{"id":"counter19","data":[{"timestamp":19,"value":19}]},{"id":"counter22","data":[{"timestamp":22,"value":22}]},{"id":"counter25","data":[{"timestamp":25,"value":25}]},{"id":"counter28","data":[{"timestamp":28,"value":28}]},{"id":"counter31","data":[{"timestamp":31,"value":31}]},{"id":"counter34","data":[{"timestamp":34,"value":34}]},{"id":"counter37","data":[{"timestamp":37,"value":37}]},{"id":"counter40","data":[{"timestamp":40,"value":40}]},{"id":"counter43","data":[{"timestamp":43,"value":43}]},{"id":"counter46","data":[{"timestamp":46,"value":46}]},{"id":"counter49","data":[{"timestamp":49,"value":49}]},{"id":"counter52","data":[{"timestamp":52,"value":52}]},{"id":"counter55","data":[{"timestamp":55,"value":55}]},{"id":"counter58","data":[{"timestamp":58,"value":58}]},{"id":"counter61","data":[{"timestamp":61,"value":61}]},{"id":"counter64","data":[{"timestamp":64,"value":64}]},{"id":"counter67","data":[{"timestamp":67,"value":67}]},{"id":"counter70","data":[{"timestamp":70,"value":70}]},{"id":"counter73","data":[{"timestamp":73,"value":73}]},{"id":"counter76","data":[{"timestamp":76,"value":76}]},{"id":"counter79","data":[{"timestamp":79,"value":79}]},{"id":"counter82","data":[{"timestamp":82,"value":82}]},{"id":"counter85","data":[{"timestamp":85,"value":85}]},{"id":"counter88","data":[{"timestamp":88,"value":88}]},{"id":"counter91","data":[{"timestamp":91,"value":91}]},{"id":"counter94","data":[{"timestamp":94,"value":94}]},{"id":"counter97","data":[{"timestamp":97,"value":97}]}],"availabilities":[{"id":"avail2","data":[{"timestamp":2,"value":"up"}]},{"id":"avail5","data":[{"timestamp":5,"value":"down"}]},{"id":"avail8","data":[{"timestamp":8,"value":"up"}]},{"id":"avail11","data":[{"timestamp":11,"value":"down"}]},{"id":"avail14","data":[{"timestamp":14,"value":"up"}]},{"id":"avail17","data":[{"timestamp":17,"value":"down"}]},{"id":"avail20","data":[{"timestamp":20,"value":"up"}]},{"id":"avail23","data":[{"timestamp":23,"value":"down"}]},{"id":"avail26","data":[{"timestamp":26,"value":"up"}]},{"id":"avail29","data":[{"timestamp":29,"value":"down"}]},{"id":"avail32","data":[{"timestamp":32,"value":"up"}]},{"id":"avail35","data":[{"timestamp":35,"value":"down"}]},{"id":"avail38","data":[{"timestamp":38,"value":"up"}]},{"id":"avail41","data":[{"timestamp":41,"value":"down"}]},{"id":"avail44","data":[{"timestamp":44,"value":"up"}]},{"id":"avail47","data":[{"timestamp":47,"value":"down"}]},{"id":"avail50","data":[{"timestamp":50,"value":"up"}]},{"id":"avail53","data":[{"timestamp":53,"value":"down"}]},{"id":"avail56","data":[{"timestamp":56,"value":"up"}]},{"id":"avail59","data":[{"timestamp":59,"value":"down"}]},{"id":"avail62","data":[{"timestamp":62,"value":"up"}]},{"id":"avail65","data":[{"timestamp":65,"value":"down"}]},{"id":"avail68","data":[{"timestamp":68,"value":"up"}]},{"id":"avail71","data":[{"timestamp":71,"value":"down"}]},{"id":"avail74","data":[{"timestamp":74,"value":"up"}]},{"id":"avail77","data":[{"timestamp":77,"value":"down"}]},{"id":"avail80","data":[{"timestamp":80,"value":"up"}]},{"id":"avail83","data":[{"timestamp":83,"value":"down"}]},{"id":"avail86","data":[{"timestamp":86,"value":"up"}]},{"id":"avail89","data":[{"timestamp":89,"value":"down"}]},{"id":"avail92","data":[{"timestamp":92,"value":"up"}]},{"id":"avail95","data":[{"timestamp":95,"value":"down"}]},{"id":"avail98","data":[{"timestamp":98,"value":"up"}]}]}
5649
gain = 23.693097392948804
```

So for the same information the grouped metrics format gives 18.79% gain when the batch size is 10, 23.69% when batch size is 100.

To me, this is a significant gain for bandwith. Especially if you consider that most data will be posted to this endpoint.

**Comment by burmanm** [comment]
If we're about to attack the amount of data transferred, then we should ditch the JSON immediately and use something lighter.

The approach of adding "type" to each given metric makes the sending of the metrics **easier** for the clients which was at least one of the major points of our API design previously. It allows simpler clients without the need for expensive grouping operations and batching. Instead of sending a single REST-request for each metric to avoid the sorting, the client could instead send them all in the order the client received them to the endpoint.

A lot simpler for many stateless applications - and by far more important from our current design perspectives than saving couple of bytes.

**Comment by tsegismont** [comment]
Le 07/07/2015 18:08, Michael Burman a écrit :
> If we're about to attack the amount of data transferred, then we should
> ditch the JSON immediately and use something lighter.

So it has to be all or nothing. I don't buy.

>
> The approach of adding "type" to each given metric makes the sending of
> the metrics *easier* for the clients which was at least one of the major
> points of our API design previously. It allows simpler clients without
> the need for expensive grouping operations and batching. Instead of
> sending a single REST-request for each metric to avoid the sorting, the
> client could instead send them all in the order the client received them
> to the endpoint.
>
> A lot simpler for many stateless applications - and by far more

Simple bash clients which only have to push a few metrics from time to 
time can use the individual endpoints.

collect/gather/send tools (agent, ptrans) will put metrics in a buffer 
and send them in batches. They'll be implemented in a high level 
language. With Java8, grouping a batch of 10-100 metrics by type is a 
matter of one line. It's not difficult nor expensive.

> important from our current design perspectives than saving couple of bytes.

I have yet to understand how grouping by type makes the entity so 
difficult to understand by a human or to deal with by a computer.

And, to me, 20-25% of payload saved is not a couple of bytes. But I may 
be as bad at maths as you're good at hyperbole :p

**Comment by burmanm** [comment]
As you're saving for bytes, you really should do that. Let me help you:

Your original documents:

```
[miburman@miranda Documents]$ ls -l *.json
-rw-rw-r--. 1 miburman miburman 580 Jul  7 20:20 bundled.json
-rw-rw-r--. 1 miburman miburman 714 Jul  7 20:20 separate.json
[miburman@miranda Documents]$
```

And when they're sent as gzips (who would send them as plain text if they want to save bandwith?):

```
[miburman@miranda Documents]$ ls -la *.gz
-rw-rw-r--. 1 miburman miburman 200 Jul  7 20:20 bundled.json.gz
-rw-rw-r--. 1 miburman miburman 206 Jul  7 20:20 separate.json.gz
[miburman@miranda Documents]$ 
```

3% difference is hardly large (and it'll only get smaller with larger documents). It's not always some collectd/gather that will create the metrics. If those are the only use cases, why are we even using REST & JSON? It's not difficult to implement more difficult protocols with these tools - using protobuf/thrift or equal would be a lot better choice in high-level languages. They would be typed, save space, have versioning etc.

**Comment by tsegismont** [comment]
Le 07/07/2015 19:25, Michael Burman a écrit :
> As you're saving for bytes, you really should do that. Let me help you:
>
> Your original documents:
>
> |[miburman@miranda Documents]$ ls -l *.json
> -rw-rw-r--. 1 miburman miburman 580 Jul  7 20:20 bundled.json
> -rw-rw-r--. 1 miburman miburman 714 Jul  7 20:20 separate.json
> [miburman@miranda Documents]$
> |
>
> And when they're sent as gzips (who would send them as plain text if
> they want to save bandwith?):
>
> |[miburman@miranda Documents]$ ls -la *.gz
> -rw-rw-r--. 1 miburman miburman 200 Jul  7 20:20 bundled.json.gz
> -rw-rw-r--. 1 miburman miburman 206 Jul  7 20:20 separate.json.gz
> [miburman@miranda Documents]$
> |
>
> 3% difference is hardly large (and it'll only get smaller with larger

Not surprising, given gzip is space-efficient. You've essentially 
verified that it is able to compress two payloads conveying the same 
information into two byte streams of almost the same size.

You have been arguing multiple times against batches of metrics grouped 
by type for performance reasons. Now you propose to use a CPU intensive 
compression algorithm, which will impact both the client and the server, 
and add latency.

I'm not against compression, it could be very useful to some users. But 
again, it doesn't have to be all or nothing: the biggest payload or the 
smallest.

> documents). It's not always some collectd/gather that will create the

True. Some users may have a lot of scripts which push just one data 
point from time to time. I do expect though that in many cases, 
agents/gatherers will play a key role.

> metrics. If those are the only use cases, why are we even using REST &
> JSON? It's not difficult to implement more difficult protocols with

Because with REST & JSON we can work in both scenarios, now.

> these tools - using protobuf/thrift or equal would be a lot better
> choice in high-level languages. They would be typed, save space, have
> versioning etc.

True. I suggest we defer the implementation until we have a stable model 
and some users failed to make the product perform well.

**Pull request merged**
