### PR TITLE
[HWKMETRICS-361] schema change management support

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
Please do not merge this yet.

**Comment by stefannegrea** [comment]
Here are the changes to be made following the review session:

1. Add a version field to each change to easily identify the software version a change is associated with it.
2. Rename the current schema file to correctly show that is a bootstrap file and add a new file for future changes. 
3. Change the logic for applying the initial schema upgrade from version 0.8.0 (or newer) if some basic criteria is met. The current version check is not sufficient because newer releases are also compatible with the upgrade.

**Comment by jsanda** [comment]
retest this please

**Pull request merged**
