### PR TITLE
[HWKMETRICS-483] bump cassalog version

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
retest this please

**Comment by mwringe** [comment]
retest please

**Comment by jsanda** [comment]
retest this please

**Comment by stefannegrea** [comment]
0.18.x does not have the optimization that avoids writes to the metrics index. The performance difference is normal.

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Pull request merged**
