### PR TITLE
[HWKMETRICS-495] upgrade to cassalog 0.4.0 and add verification checks

### PR DESCRIPTION
**Pull request by jsanda**
The verification checks are used in restart scenarios to help determine whether
or not a change, such as creating a table, has already been applied. Applying
the schema change and updating the changelog table cannot be done atomically
so we need to do some extra work to make sure we are in a known, good state.

### CODE REVIEW

**Comment by jshaughn** [comment]
@jsanda As we discussed, this will require a similar upgrade to alerting such that dependencies are not out of sync between the two wars.

**Comment by stefannegrea** [comment]
@jsanda, I see this error in the build logs:

```
05:04:05,815 FATAL [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200006: An error occurred trying to connect to the Cassandra cluster: groovy.lang.MissingMethodException: No signature of method: org.cassalog.core.CqlChangeSet.verify() is applicable for argument types: (schema-0_15_0$_run_closure1$_closure6) values: [schema-0_15_0$_run_closure1$_closure6@39617ef7]
```

**Comment by jsanda** [comment]
@stefannegrea This is the outstanding class loading issue I mentioned to you yesterday with the EAR. Metrics is picking up the Cassalog dependency from Alerts. For the short term we need to make common dependencies are in sync with respect to version. Alerts needs to upgrade Cassalog any way so I have already submitted [this PR](https://github.com/hawkular/hawkular-alerts/pull/233). Going forward after this upcoming release, we need to sort out the class loading issues. Once the Alerts PR is merged and we update the src dep, this problem should go away. I tested with only the Metrics WAR and everything works as expected.

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Pull request merged**
