### PR TITLE
HWKMETRICS-344 - Added Secret Store integration

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
Thanks @jpkrohling!

**Comment by jmazzitelli** [comment]
did you run the full server-with-agent with this fix? did it work for you? Because I just rebuild with this and its still not working, though with a different error:

ERROR org.hawkular.agent.monitor.storage.MetricsOnlyStorageAdapter  - HAWKMONITOR010010: Failed to store metric data: {"counters":[{"data":[{"value":0,"timestamp":1454017329184}],"id":"MI~R~[6f9d3775-410f-4f9a-bd76-cc6e9f2979c2/Local~/deployment=hawkular-wildfly-agent-download.war]~MT~Undertow Metrics~Expired Sessions"}],"availabilities":[],"gauges":[]}
java.io.IOException: status-code=[400], reason=[Bad Request], url=[http://127.0.0.1:8080/hawkular/metrics/metrics/data]

**Pull request merged**
