### PR TITLE
HWKMETRICS-103

### PR DESCRIPTION
**Pull request by mwringe**
Add liveness probes and postStartup hooks to the hawkular metrics containers.
Update to use kubernetes v1beta03 api.

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by tsegismont** [comment]
> Please use the curl -H 'Hawkular-Tenant: status' instead and not the fallback

Well I'd say that we'd rather update the TenantFilter so that no tenant header is needed when sending requests to `status`

**Comment by mwringe** [comment]
If HWKMETRICS-104 goes in, I wont be using the ping endpoint for this.

I view the /ping endpoint as being more of a check that the user can access their tenants endpoint (eg still requires a tenant id, user authentication token, etc). But that requires the security layer to be in place.

**Comment by tsegismont** [comment]
Then shouldn't we finish HWKMETRICS-104 first? PR #225 says "do not merge yet"

**Comment by mwringe** [comment]
OK, its been update to use the /status endpoint instead of /ping.

**Comment by tsegismont** [comment]
Looks good to me. Thanks!

**Pull request merged**
