### PR TITLE
HWKMETRICS-399 Make Metrics independent of Hawkular Accounts

### PR DESCRIPTION
**Pull request by stefannegrea**

### CODE REVIEW

**Comment by stefannegrea** [comment]
This PR should be ready for merge after the src-dep introduced in the first commit is removed.

**Comment by ppalaga** [comment]
@stefannegrea commons 0.7.1.Final released.

**Comment by jsanda** [comment]
I think the hawkular-server-tests module needs to be updated as well. AuthenticationITest.groovy can probably be deleted and we need to remove the dependency on the accounts feature pack.

**Comment by stefannegrea** [comment]
@jsanda, I removed the tests you mention, however we will probably need to rework that entire module later since it is not running at the moment as part of the build.

**Comment by stefannegrea** [comment]
retest this please

**Pull request merged**
