### PR TITLE
HWKMETRICS-347 Hawkular Component should accept metric input from the bus

### PR DESCRIPTION
**Pull request by tsegismont**
HWKMETRICS-347 Hawkular Component should accept metric input from the bus

Added a bean which listens to metric data coming from the bus and persists it with the MetricsService.

### CODE REVIEW

**Comment by tsegismont** [comment]
**Please do not merge yet**

I am going to send an email to the devel list tonight to explain why this could be useful.

**Comment by tsegismont** [comment]
The PR lacks an integration test. I will add it later if this PR is merged. I have tested this PR manually.

**Comment by stefannegrea** [comment]
Can you please at least open a JIRA to track the integration tests missing prior to merging?

**Comment by jpkrohling** [comment]
HWKMETRICS-352 for the integration tests.

**Comment by ppalaga** [comment]
I have taken cfed95e of @tsegismont , removed the `version.org.hawkular.commons` prop from the `hawkular-metrics-component` and put on top of https://github.com/hawkular/hawkular-metrics/pull/455 . I did this only because @tsegismont is out of office and we depend on this in Hawkular main.
This PR is thus supersed by https://github.com/hawkular/hawkular-metrics/pull/455 and can be closed.

**Comment by stefannegrea** [comment]
Why was this PR closed??

**Comment by ppalaga** [comment]
@stefannegrea see https://github.com/hawkular/hawkular-metrics/pull/445#issuecomment-183338204

**Comment by ppalaga** [comment]
@stefannegrea could we please get https://github.com/hawkular/hawkular-metrics/pull/455 reviewed and merged rather than keeping the present PR reopened? #455 fixes the present PR and solves all we need for Hawkular M10.

**Comment by stefannegrea** [comment]
@ppalaga, this PR has code for the bus integration. How does #455 replace that code?

**Comment by jpkrohling** [comment]
The commit of this PR is included in the #455 .

**Comment by stefannegrea** [comment]
Thanks for clarifying that. I did not notice the commit.

**Pull request closed without merging**
