### PR TITLE
[HWKMETRICS-359] upgrade C* driver to version 3.0.0

### PR DESCRIPTION
**Pull request by jsanda**
There were some changes to the SSLOptions API in the driver. See
https://datastax-oss.atlassian.net/browse/JAVA-841 for details.

### CODE REVIEW

**Comment by FilipB** [comment]
retest this please

**Comment by tsegismont** [comment]
LGTM. Waiting for 0.13.0 to be released and 0.14.0 item to be created in JIRA before merging.

**Comment by stefannegrea** [comment]
@jsanda, do you mind rebasing on master?

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Pull request merged**
