### PR TITLE
HWKMETRICS-342 ptrans should work with a Metrics server protected by Accounts

### PR DESCRIPTION
**Pull request by tsegismont**
Added new config properties:
- server.type: metrics/hawkular
- auth.id
- auth.secret
- persona.id

tenant config property is now only used when server.type == metrics

### CODE REVIEW

**Comment by tsegismont** [comment]
retest this please

**Comment by tsegismont** [comment]
Would you mind to review @pilhuhn ?

**Comment by tsegismont** [comment]
Can someone please review?

**Comment by tsegismont** [comment]
Can we get this merged before 0.13 is released? The PR has been available for review for a week now. Thanks.

**Comment by jsanda** [comment]
A couple questions. 

First, do we need to worry about accounts integration any more? 

Second, could you add an integration test?

**Comment by tsegismont** [comment]
Le 26/02/2016 15:42, jsanda a écrit :
> A couple questions.
>
> First, do we need to worry about accounts integration any more?

I'm not aware of any plans to stop securing Hawkular with Accounts. If 
that changes, then I'll update ptrans as needed. In any case, we're just 
authenticating with HTTP Basic auth, so it shouldn't change much if 
Accounts is involved or not.

>
> Second, could you add an integration test?

I tested this code manually but chose not add such an integration test 
because, IMHO the cost (start both a Metrics and a Hawkular server 
during the build) outweighs the benefit.

**Comment by tsegismont** [comment]
Thank you John.

**Pull request merged**
