### PR TITLE
Move to  Travis container based infra

### PR DESCRIPTION
**Pull request by tsegismont**
Do not merge yet. Initial commit and testing.

### CODE REVIEW

**Comment by tsegismont** [comment]
Ready for review/merging.

**Comment by tsegismont** [comment]
Restarted the build, it failed because of CountersITest

**Comment by burmanm** [comment]
mm, this time these could really use some squashing to be able to revert more easily if things don't work in reality

**Comment by tsegismont** [comment]
They do work. This PR has been built on the new infra. See:
https://travis-ci.org/hawkular/hawkular-metrics/builds/70343009
https://travis-ci.org/hawkular/hawkular-metrics/builds/70352738

**Comment by tsegismont** [comment]
Le 10/07/2015 17:05, Michael Burman a écrit :
> Merged #285 <https://github.com/hawkular/hawkular-metrics/pull/285>.

Thanks for reviewing. If you have a look at the current master build and 
see Maven repo downloads again, don't panic, this is expected :)

Travis uses different caches for branches and it's the first time master 
is built on the new infra.

++

**Pull request merged**
