### PR TITLE
[HWKMETRICS-454] use deflate compressor for data table

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
retest this please

**Comment by jsanda** [comment]
retest this please

**Comment by burmanm** [comment]
retest this please

**Comment by burmanm** [comment]
retest this please

**Comment by jsanda** [comment]
retest this please

**Comment by jsanda** [comment]
retest this please

**Comment by burmanm** [comment]
The disk usage benefits outweight any performance issues, so I'll merge this.

**Comment by FilipB** [comment]
Just clarifying that this introduced performance drop in throughput 2%, baselines are updated.

**Comment by FilipB** [comment]
I can see 30% improvement in used disk space for gauges and counters. Results for avail are unstable for some reason

**Pull request merged**
