### PR TITLE
[HWKMETRICS-771] compressBlock will check for all possible blocks to compress

### PR DESCRIPTION
**Pull request by burmanm**
WIP, will check for bugs later..

### CODE REVIEW

**Comment by jsanda** [comment]
I have restarted travis several times. It consistently fails with the now infamous:

```
Failed tests: 
  DataAccessITest.testFindAllDataFromBucket:271 Number of onNext events differ; expected: 10000, actual: 0 (1 completion)
```

**Comment by jsanda** [comment]
With the new flatMap call in MetricsServiceImpl.compressBlock, could we compress multiple tables concurrently? Even aside from the job scheduler bug, I think it is quite possible to end up with tables that do not compressed when they are supposed to. If there is any error, e.g., read or write timeout, the observables will fail fast.

**Comment by jsanda** [comment]
I would like to see some logging in MetricsServiceImpl.compressBlock:

* Log a warning on error
* Debug message that lists the timestamps emitted from datAccess.findExpiredTables

**Comment by burmanm** [comment]
There's concurrency for reading data for a single table:

public Completable compressBlock(long jobStartTimeSlice, int pageSize, int maxConcurrency) {

But it's not used (I didn't find it necessary, the compression job is quite quick and if we increase concurrency we might harm the system's stability)

**Comment by jsanda** [comment]
> But it's not used (I didn't find it necessary, the compression job is quite quick and if we increase concurrency we might harm the system's stability)

Increased concurrency is my concern as well and why I ask. I am referring to this outer most flatMap:

```java
    public Completable compressBlock(long jobStartTimeSlice, int pageSize, int maxConcurrency) {
        return Completable.fromObservable(
                Observable.from(dataAccess.findExpiredTables(jobStartTimeSlice))
                        // Will this flatMap result in concurrent execution?
                        .flatMap(startTimeSlice ->
                        // ...
                        );
        // ....
        );
}
```

**Comment by jsanda** [comment]
@burmanm forgot to ask before, can you please create a ticket for the PR? Then I will merge. Thanks.

**Pull request merged**
