### PR TITLE
HAWKULAR-985 - Removed direct dependency on secret store.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jpkrohling** [comment]
Is this expected? Travis results:
```
  TaskSchedulerITest.executeSingleTask:147 Number of onNext events differ; expected: 1, actual: 3

  TaskSchedulerITest.executeTaskThatRepeatsTwice:221 Number of onNext events differ; expected: 2, actual: 4

  TaskSchedulerITest.executeTasksFromMultipleGroupsMultipleTimes:370 Not completed!
```

**Comment by tsegismont** [comment]
@jpkrohling no it's not. but I'm not sure the Task scheduler is still used anyway

**Comment by jpkrohling** [comment]
In any case, I ran the build locally with `mvn clean install`:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Hawkular Metrics ................................... SUCCESS [  6.894 s]
[INFO] Hakwular Metrics RxJavaDriver ...................... SUCCESS [  2.280 s]
[INFO] Hawkular Metrics Schema Manager .................... SUCCESS [  1.416 s]
[INFO] Hawkular Metrics Task Queue ........................ SUCCESS [ 10.683 s]
[INFO] Hawkular Metrics Model ............................. SUCCESS [  3.133 s]
[INFO] Hawkular Metrics Core Service ...................... SUCCESS [ 25.483 s]
[INFO] Hawkular Metrics REST API Util ..................... SUCCESS [  0.734 s]
[INFO] Hawkular Metrics JAX-RS 2.0 API .................... SUCCESS [ 10.284 s]
[INFO] Hawkular Metrics Bus ............................... SUCCESS [ 22.053 s]
[INFO] Hawkular Metrics Component ......................... SUCCESS [  1.580 s]
[INFO] Hawkular Metrics Integration Tests ................. SUCCESS [  1.133 s]
[INFO] Hawkular Metrics Rest Tests for JAX-RS 2.0 ......... SUCCESS [ 39.385 s]
[INFO] Hawkular Metrics Rest Tests with Hawkular server ... SUCCESS [ 49.395 s]
[INFO] Hawkular Metrics Load Tests ........................ SUCCESS [  0.548 s]
[INFO] Hawkular Metrics clients ........................... SUCCESS [  0.860 s]
[INFO] hawkular-metrics-clients-common .................... SUCCESS [  1.487 s]
[INFO] Protocol Translator ................................ SUCCESS [01:12 min]
[INFO] Hawkular Metric Containers ......................... SUCCESS [  0.399 s]
[INFO] Cassandra Seed Provider ............................ SUCCESS [  0.671 s]
[INFO] Hawkular Metrics OpenShift Integration ............. SUCCESS [  0.511 s]
[INFO] Hawkular Metrics JAX-RS API - Openshift ............ SUCCESS [  1.121 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:15 min
[INFO] Finished at: 2016-02-04T12:52:29+01:00
[INFO] Final Memory: 134M/793M
[INFO] ------------------------------------------------------------------------
```

**Comment by tsegismont** [comment]
@jpkrohling the PR looks good to me.

**Comment by tsegismont** [comment]
Thanks @jpkrohling !

**Pull request merged**
