### PR TITLE
[HWKMETRICS-50] return distinct avails as determined by state change

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
This is not ready to be merged yet. I need to add an unknown availability state.

**Comment by jsanda** [comment]
I have added an unknown availability type. This PR is ready for review.

**Comment by mtho11** [comment]
Once this is merged can it be pushed to kettle as well, so the UI can use it?

**Comment by stefannegrea** [comment]
@mtho11 we need to update kettle to use version 0.3.2-SNAPSHOT of Hawkular Metrics. I will take care of that.

**Pull request merged**
