### PR TITLE
Upgrade netty 4.0.33.Final -> 4.0.35.Final

### PR DESCRIPTION
**Pull request by pgier**
This syncs with current version used by Wildfly

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
@pgier, looks like ptrans tests fail consistently with your change.

**Comment by stefannegrea** [comment]
ok to test

**Comment by burmanm** [comment]
Careful with this, Cassandra driver has its own version of netty also (newest updates have 4.0.37.Final)

**Comment by stefannegrea** [comment]
@pgier, do you mind rebasing on latest master? We have switched the tests to run against the ear distribution of Hawkular Metrics.

**Comment by stefannegrea** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by FilipB** [comment]
retest this please

**Comment by stefannegrea** [comment]
@pgier, is this PR still needed?

**Comment by pgier** [comment]
It's not needed for the current release, so feel free to close it.

**Pull request closed without merging**
