### PR TITLE
Require the proper Cassandra version 3.5 in README.adoc

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@tsegismont this is just an update of `README.adoc`. I am introducing an AsciiDoc variable for the version of Cassandra. Here is how it looks rendered: https://github.com/ppalaga/hawkular-metrics/blob/160426-readme/README.adoc

**Comment by tsegismont** [comment]
Thanks Peter. Can't merge right now as we are still not sure if 3.5 is "required" for Metrics. See https://issues.jboss.org/browse/HWKMETRICS-394

**Comment by stefannegrea** [comment]
@ppalaga, based on the JIRA discussion we want the verbiage to be `3.4 or later`. I will merge the PR once that change is made.

**Comment by ppalaga** [comment]
@stefannegrea d20cc33 uses `3.4` cassandra version.

**Comment by stefannegrea** [comment]
Thanks @ppalaga!

**Comment by stefannegrea** [comment]
retest this please

**Pull request merged**
