### PR TITLE
Migrate API, Core and Test utils from TestNG to jUnit

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by jsanda** [comment]
There has already been a lot of discussion on this, so I decided it would be good for me to check out the branch, take a closer look at the code, and run the tests. I discovered that running tests individually does not work. My apologies if that has already been noted and if I just missed that. @ppalaga can you update the PR so that running tests individually works again?

**Comment by ppalaga** [comment]
Sorry for the inconvenience, yes it is on my TODO. I hope I'll be able to do it on Monday.

**Comment by ppalaga** [comment]
@jsanda, @tsegismont I simplified the Junit setup in 8ab70db , however, when running a single test from Eclipse, I am getting `InvalidQueryException: Keyspace 'rhq' does not exist` which probably has to do with `src/main/script/schema.groovy` that is run by maven but not by the IDE. Any ideas or other comments?

**Comment by jsanda** [comment]
In ```MetricsTestUtils.getKeyspace```, make the default ```rhqtest```. That will be consistent with what the maven build uses and should resolve you problem.

**Comment by ppalaga** [comment]
@jsanda yes, thanks that helped. In b21a37a2aa1adbcf441411c17d6b67ab19ebaf37 I squashed all my commits together and rebased on top of the recent master. Any other comments?

**Comment by tsegismont** [comment]
Looks good to me. In another PR we can try to factor out the class rule code.

**Comment by ppalaga** [comment]
> factor out the class rule code
@tsegismont what do you dislike about how it is now?

**Comment by tsegismont** [comment]
Le 07/01/2015 11:11, Peter Palaga a écrit :
> factor out the class rule code
> @tsegismont <https://github.com/tsegismont> what do you dislike about
> how it is now?

Maybe it could be a bit shorter. It's fine as it is now. The purpose of 
*this* PR was to move to jUnit. Maybe in another PR we can get close to 
what Achilles provides (short rule definitions with a builder API).

**Comment by ppalaga** [comment]
@tsegismont OK, no problem with that (and I do not plan to be active).

**Comment by jsanda** [comment]
I realize that the purpose of this PR was to move to JUnit. The code now looks very similar to what a TestNG solution would look like. To be honest, I am still concerned about whether or not JUnit provides feature parity with TestNG for things like grouping testing, dependent tests, and ordering tests. Maybe JUnit does, and I am just not aware. While the decision has been made (for reasons not entirely clear to me) to migrate to JUnit, maybe we need to revisit that decision if JUnit does not adequately provide features/functionality that are really useful for integration tests like these.

**Comment by ppalaga** [comment]
> grouping testing, dependent tests, and ordering tests

@jsanda , do we need that?

> migrate to JUnit, maybe we need to revisit that decision

rhq-devel@lists.fedorahosted.org is probably the proper place. It would be nice if the discussion is over (and this PR either rejected or merged) before the rename.

**Comment by tsegismont** [comment]
I'd like to merge this PR considering that there is a consensus on the junit way not being:
* more/less verbose
* easier/harder to understand

A junit/testng debate has no rational ending but I'm not entitled to close it.

**Comment by jsanda** [comment]
Please do not merge this PR. I will send an email today to this dev list. The discussion in this PR has been insightful particularly that it has not convinced me that JUnit provides feature parity with TestNG for integration testing. If that turns out to be the case, then I want to push back on completely migrating to JUnit.

**Comment by ppalaga** [comment]
@jsanda  Please post your position on the dev list so that we can come closer to a resolution.

**Comment by jsanda** [comment]
Hi Peter. Sorry for the delayed response. The number of integration tests is going to steadily increase, and I still have concerns about losing some of the functionality we become accustomed to using with TestNG. For now, I want to stick with TestNG for the integration tests.

**Comment by ppalaga** [comment]
@jsanda sorry I have missed your post last week. Could you please post a short summary of your TestNG pros and jUnit cons to hawkular-dev list? Preferring JUnit rather then TestNG is the present convention. It would be fair to revert it as transparently as possible, i.e. inform others and give them a chance to discuss.

**Comment by jsanda** [comment]
Closing since this has been further discussed on the hawkular-dev mailing list.

**Comment by ppalaga** [comment]
OK, John, I am giving up with this particular PR. But would you please try to answer the questions I asked on the list? I am especially interested on your view on the status of jUnit in Metrics. Is it banned altogether?

**Pull request closed without merging**
