### PR TITLE
Remove ui/explorer

### PR DESCRIPTION
**Pull request by burmanm**
Removes the explorer interface as it's not working and won't be fixed in the short term. This removes the requirement of node.js/npm from the build and speeds up the building process also.

### CODE REVIEW

**Comment by tsegismont** [comment]
retest this please

**Comment by tsegismont** [comment]
+1

**Comment by stefannegrea** [comment]
Confirmed with @mtho11 that we can remove this content and the PR is good to be merged. @mtho11 will resurrect the code later. 

The Jenkins job failure can be ignored.

**Comment by FilipB** [comment]
retest this please

**Pull request merged**
