### PR TITLE
[HWKMETRICS-219]Fix counter rate calculation

### PR DESCRIPTION
**Pull request by auszone**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by stefannegrea** [comment]
@auszone, can you please rebase this PR on latest master?

**Comment by auszone** [comment]
@stefannegrea rebased

**Comment by tsegismont** [comment]
Thanks for contributing @auszone

This part of the code is no longer used and I'm not sure about @jsanda 's plans for the futures. Could we wait for him to be back before merging?

**Comment by stefannegrea** [comment]
@jsanda, do you mind reviewing this change?

**Comment by jsanda** [comment]
The change looks good. The code is not used, but the PR does fix a bug and gets a community member a bit more involved and familiar with the project. I am ok with merging.

**Comment by stefannegrea** [comment]
Thanks @jsanda for the review!

Thanks @auszone for the PR. Really appreciated!

**Pull request merged**
