### PR TITLE
Wildfly Maven Plugin: skip server start when tests are disabled

### PR DESCRIPTION
**Pull request by tsegismont**
Upgrade Wildfly Maven Plugin version -> now we can skip server start when tests are disabled

### CODE REVIEW

**Comment by tsegismont** [comment]
Build failed initially because the new Wildfly Maven plugin version requires to use `<javaOpts>` instead of `<jvmArgs>`.

Note that there's a warning which appears now when building the whole project. I've reported the issue: https://github.com/wildfly/wildfly-maven-plugin/issues/31

**Comment by stefannegrea** [comment]
@tsegismont ready to be merged?

**Comment by tsegismont** [comment]
It can be merged, if we all agree that the warning in the build log is not a blocker.

The report I've made to the Wildfly Maven Plugin issue tracker has been categorized has a minor bug. It may be fixed in the next version.

**Comment by tsegismont** [comment]
Rebased on master. I've [pushed a fix for the minor bug](https://github.com/wildfly/wildfly-maven-plugin/pull/32) (build warning, see above). Should we merge or wait until a new version of the plugin is released?

**Comment by tsegismont** [comment]
Looks like setting different ports for ptrans Wildfly servers (see #171) makes the warning go away... Merging.

**Pull request merged**
