### PR TITLE
[HWKMETRICS-218] [HWKMETRICS-284] handle counter reset events

### PR DESCRIPTION
**Pull request by jsanda**
We now filter out those windows in which the second value is less than the
first.

### CODE REVIEW

**Comment by stefannegrea** [comment]
So this PR closes https://issues.jboss.org/browse/HWKMETRICS-284 too?

**Comment by jsanda** [comment]
>So this PR closes https://issues.jboss.org/browse/HWKMETRICS-284 too?

Yes

**Comment by stefannegrea** [comment]
retest this please

**Comment by stefannegrea** [comment]
Thanks @jsanda!

**Pull request merged**
