### PR TITLE
Upgrade to hawkular-parent 40, Accounts 2.0.23.Final and Commons 0.5.0.Final

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jsanda this brings versions of components and hawkular-parent that are compatible with Cassandra 3.4. You'll probably want to merge/cherry-pick this into your Cassandra 3.4 branch.

**Comment by ppalaga** [comment]
9624794 brings hawkular-parent 41 with Cassandra 3.5 and compatible Commons and Accounts.

@jsanda what is the status of migration to Cassandra 3.x in Metrics? I see master still being tested against 2.x. You said you have a branch with Cassandra 3.x? - Could you please show it to me so that I can try to integrate with Agent and Hawkular main?

**Comment by jsanda** [comment]
The necessary changes have already been merged. We just need to update the travis configuration. I have been developing and testing against C* 3.x.

**Comment by ppalaga** [comment]
037d1c4 upgrades to Cassandra 3.5.x in the Travis script.

**Comment by ppalaga** [comment]
1e9a1bd fixes some issues in `.travis.install.cassandra.sh`.

**Comment by ppalaga** [comment]
@jsanda both checks passed. Is this good to merge now?

**Pull request merged**
