### PR TITLE
[HWKMETRICS-650] Upgrade rxjava 1.2.6 -> 1.2.7

### PR DESCRIPTION
**Pull request by pgier**
Matches version with vert.x platform

### CODE REVIEW

**Comment by burmanm** [comment]
1.2.9 is already out, I don't think it makes sense to update to older version.

**Comment by stefannegrea** [comment]
This was done to align project dependencies with other projects.  @burmanm, do you mind opening a JIRA and PR to update master to the latest version?

**Comment by stefannegrea** [comment]
Thank you @pgier!

**Comment by burmanm** [comment]
I'm not sure it makes any sense to align with projects that we're not dependant on. What's the point of that process?

**Comment by burmanm** [comment]
Especially since this was targeting master.

**Pull request merged**
