### PR TITLE
findMetrics did not follow consistent gauges naming

### PR DESCRIPTION
**Pull request by burmanm**
type should follow the same naming convention than rest of the REST-API (even if plural doesn't sound right). I still would prefer moving this to PathParam ..

### CODE REVIEW

**Comment by tsegismont** [comment]
>  I still would prefer moving this to PathParam ..

Agreed, this endpoint is more of RPC-style, whereas splitting it into `/{tenantId}/gauges`, ... etc conforms to resource oriented design, which was one of the motivations of the JAX-RS API remake.

Too bad [the comments in the corresponding PR](https://github.com/hawkular/hawkular-metrics/pull/197#discussion_r28882378) were not answered before it was merged.

**Comment by tsegismont** [comment]
I agree with Micke. +1 for merging

**Comment by jsanda** [comment]
I suppose it is not a big deal either way, but the plural makes sense to me and does seem more consistent.

**Comment by stefannegrea** [comment]
We will need to rebase this on the latest master. 

@burmanm, can you please update the MetricType.fromTextCode to support parsing both single and plural for gauge? In my comment I was more concerned about the domain model not supporting singular. I am ok with the REST API using plural.

**Comment by stefannegrea** [comment]
@burmanm the merge commit was really confusing. Do you mind just force rebasing on master. The primary changes are all good, but the diff for the second commit is really confusing.

**Comment by burmanm** [comment]
Will redo later.

**Comment by stefannegrea** [comment]
@burmanm thanks for the work. Sorry it did not get merged in time.

**Pull request closed without merging**
