### PR TITLE
[HWKMETRICS-542] set driver max connections == core connections

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
retest this please

**Comment by stefannegrea** [comment]
@jsanda, do you mind rebasing on master?

**Comment by FilipB** [comment]
Performance results for availability and strings (those runs are using bigger msgs) have been very unstable lately. Several manual runs didn't show any drop so it's ok to merge.

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Comment by FilipB** [comment]
This PR improved significanty issue described in https://issues.jboss.org/browse/HWKMETRICS-542 but it also introduced ~13% drop for the smallest msgs. Change for other msgs sizes is +- 3%

**Pull request merged**
