### PR TITLE
Emend the comment

### PR DESCRIPTION
**Pull request by auszone**

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by pilhuhn** [comment]
Thanks @auszone :+1:

**Comment by auszone** [comment]
@pilhuhn :smile: I also factored out some code #447 . Wondering if there are any other issues that I can work on as a beginner.

**Comment by pilhuhn** [comment]
@auszone I want to leave #447 from the metrics core team to verify, as they know the intend behind this better than I do.
You could start having a look at the jiras at https://issues.jboss.org/projects/HAWKULAR/issues for all of Hawkular or any of the HWK* jiras like https://issues.jboss.org/projects/HWKMETRICS/issues for Hawkular-Metrics to see if you find something.

**Pull request merged**
