### PR TITLE
[HWKMETRICS-797] wait for schema agreement before preparing queries

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by jsanda** [comment]
@rubenvp8510 can you please review/test this?

I created a test in [this branch](https://github.com/jsanda/hawkular-metrics/tree/temptable-test) that you can use to reproduce the exception. See the [commit log msg](https://goo.gl/2b58kZ) for instructions on how to set up a multi-node C* cluster using ccm.

**Comment by rubenvp8510** [comment]
This still failing sometimes to me. I put an extra log with "Waiting for schema agreement to prepare statements................." to make sure that block of code is reached. 

EBUG 2018-07-23 14:08:58,456 [RxIoScheduler-3] org.hawkular.metrics.core.service.DataAccessImpl$TemporaryTableStatementCreator:lambda$onTableAdded$0:1374 - Waiting for schema agreement to prepare statements.................
Exception in thread "RxIoScheduler-3" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorNotImplementedException: unconfigured table data_temp_2018072018
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table data_temp_2018072018
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at org.hawkular.metrics.core.service.DataAccessImpl.prepareTempStatements(DataAccessImpl.java:392)
	at org.hawkular.metrics.core.service.TestDataAccessFactory$1.prepareTempStatements(TestDataAccessFactory.java:53)
	at org.hawkular.metrics.core.service.DataAccessImpl$TemporaryTableStatementCreator.lambda$onTableAdded$0(DataAccessImpl.java:1380)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)

**Comment by jsanda** [comment]
Based on the stack trace it looks like you are running the test against a version that does not have the change. Sorry, my instructions were not very clear. The test branch does **not** have the fix. This was intentional so that you could see the error easily reproduced. You will want to rebase my hwkmetrics-797 branch on top of temptable-test branch and you should (hopefully) no longer see the error.

**Comment by rubenvp8510** [comment]
Not sure if this helps: https://datastax-oss.atlassian.net/browse/JAVA-1754

**Comment by rubenvp8510** [comment]
@jsanda this is my branch with both, the test and the fix. https://github.com/rubenvp8510/hawkular-metrics/tree/test-fail-fix

**Comment by jsanda** [comment]
@rubenvp8510 aside from the test failures, I am not that I like my latest commit based on your observation that we could briefly have schema agreement on the old version. Rather than doing a token range scan to check for schema agreement, I think it might be better to do the following when the listener is called:

* Wait for some initial delay to allow for schema changes to propagate
* Created prepared statements
* If creating prepared statements fails, retry after some delay
* Keep retrying until either success or shutdown

**Comment by rubenvp8510** [comment]
@jsanda that sounds good. I think those steps cover all scenarios.

**Comment by jsanda** [comment]
@rubenvp8510 I pushed commit last night with the new logic.

**Comment by rubenvp8510** [comment]
@jsanda I've already tested this, it works and looks good.

Only one minor comment. Do you think is good to have the stack of the exception on logs or just fails with a clear message: " Failed to prepare statements for table data_temp_2018072100,  will retry in 5000 milliseconds"?.

Another thing is, is there a max number of retries? 

Other than that, this looks good.

**Comment by jsanda** [comment]
I wondered the same thing about the exception. We probably don’t need the
whole stack trace, just the short message. I am not sure that I want to
limit the retries because we could potentially end up with the same problem
that we currently have.

**Comment by jsanda** [comment]
@rubenvp8510 I just pushed a commit that updates the logging. If it looks good, can you please squash and merge.

**Pull request merged**
