### PR TITLE
Allow rate queries for read-only users

### PR DESCRIPTION
**Pull request by jotak**
The POST endpoint /counters/rate/query is used to read data, it should be authorized for read-only users (similar to /counters/raw/query)

### CODE REVIEW

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by burmanm** [comment]
ok to test

**Comment by burmanm** [comment]
@mwringe Do you need this in the 0.18.x branch?

**Comment by mwringe** [comment]
Yes, we will need this in the 0.18 branch as well

**Pull request merged**
